### ISSUE TITLE
github pageを作る

### ISSUE THREAD

**Issue by MSakamaki** [chirimen-oh/any-issues#1]
- [x] jekyllでページを作る。
- [ ] コンテンツの概要を整える。
- [x] SEO 対策
  - http://jekyll.tips/tutorials/seo/
- [ ] `chirimen.org`と関連づける

**Comment by MSakamaki** [comment]
じぇきる！
https://help.github.com/articles/using-jekyll-as-a-static-site-generator-with-github-pages/

**Comment by gurezo** [comment]
:+1:

**Comment by MSakamaki** [comment]
とりまgithub.ioドメインでページ公開 （jekyllのテンプレ）
http://chirimen-org.github.io/

これからちょくちょく弄ります。

**Comment by gurezo** [comment]
:+1:

**Comment by MSakamaki** [comment]
作ったのでclose、以降問題が有れば
https://github.com/chirimen-org/chirimen-org.github.io
に投稿してください
