### ISSUE TITLE
RELEASEリポジトリを作る

### ISSUE THREAD

**Issue by MSakamaki** [chirimen-oh/any-issues#10]
### 置かれるもの
- [x] LICENCE
- [x] 回路図
- [x] B2G関連

**Comment by satakagi** [comment]
ソフトには、release以外のリポがあって、ハードはreleaseのリポしかない理由はなぜ？

**Comment by satakagi** [comment]
releaseには、ファームウェアのバイナリだけを置きますか？　ソースコードも置きますか？

**Comment by satakagi** [comment]
ファーむぇあ書き込みツールとかは置きますか？

**Comment by dadaa** [comment]
ハードはリリース以外のものってあります？
あるとすれば，Hardware リポジトリ作りましょうか

**Comment by dadaa** [comment]
ソフトは，B2G を submodule として置けばよいかと思います
// 以前，議論して，そうしようとなったと思います
書き込みツールは置かなくてよいかと思います

**Comment by satakagi** [comment]
ステッピングモーターとかの基板とか

2016年4月26日 13:32 dadaa notifications@github.com:

**Comment by dadaa** [comment]
あー，なるほど
ハードウェア単体のライセンスは CC で，CHIRIMEN ライセンスにはかからないですよね？

**Comment by naokisekiguchi** [comment]
ビルドしたCHIRIMENイメージをどこかに置くべきだと思います。RELEASEレポジトリのreleasesにアップすべきかと思いましたがどうでしょう？

**Comment by dadaa** [comment]
最終的にできる update.img が 300M を超えちゃっているので，
https://help.github.com/articles/conditions-for-large-files/
の制約にひっかかっちゃいそうです

**Comment by naokisekiguchi** [comment]
@dadaa こちら https://github.com/chirimen-org/CHIRIMEN-tools/releases に過去のイメージがアップされています。zipファイルは150M前後ですが、ダウンロードしたファイルを解凍すると300Mを超えているので、おそらくzip圧縮後にアップすることは可能かと思われます。

**Comment by dadaa** [comment]
@naokisekiguchi ほえー，ほいじゃ大丈夫そうですね!

**Comment by satakagi** [comment]
自分でビルする人は まず少数派ですので、ビルドイメージは一番みんながアクセスしやすい場所に置いておくべきですね。
ちなみに、releaseはアクセスしやすい構造と導線作れます？

2016-04-26 21:12 GMT+09:00 dadaa notifications@github.com:

**Comment by naokisekiguchi** [comment]
@satakagi 
https://github.com/chirimen-org/CHIRIMEN-tools/releases/tag/v2.5-20160109
こんな感じで特定のreleaseへのリンクが貼れます。

**Comment by dadaa** [comment]
現状 release-candidate なので，明日，release に rename しましょう
