### ISSUE TITLE
MFT2016 ブースイベントのタイムスケジュール作成依頼

### ISSUE THREAD

**Issue by gurezo** [chirimen-oh/any-issues#101]
ブースイベントのタイムスケジュール書いてもらう。

**Comment by kohichi000000** [comment]
オライリーさんに依頼しました。ブースの目の前に下記を書いたスタンドを立てる予定。
こんな感じです。

「CHIRIMENの紹介」のところでCHIRIMENの紹介＋LT大会をやりますー

8/6(土)
12:30- 「私だけのプラネタリウム作り」（会場見学ツアーを含む、女子中高生対象）
14:55- au x HAKUTO MOON CHALLENGEご紹介
15:30- CHIRIMENのご紹介
16:30- タッチアンドトライ
17:00- au x HAKUTO MOON CHALLENGEご紹介
18:00- タッチアンドトライ

8/7(日)
10:00- タッチアンドトライ
11:00- CHIRIMENのご紹介
12:00- 坂井直樹氏プレゼンツ　パネルトーク「Maker movementは宇宙まで（仮）」
14:10- 「地球外生物のテクノブローチをつくろう」
15:00- au x HAKUTO MOON CHALLENGEご紹介
16:00- CHIRIMEN x HAKUTO「CHIRIMENでできるHAKUTOのミッションをガチで考える」
