### ISSUE TITLE
chirimen.orgにslack招待リンクの割り当て

### ISSUE THREAD

**Issue by gurezo** [chirimen-oh/any-issues#106]
### サイト配置をする事を忘れない為にissueを立てる。
- [Chirimen Open Hardware Community slack 招待フォーム](https://docs.google.com/forms/d/e/1FAIpQLScyfyFZbe7uZbQQzSQq78tRqtRKWXvmDRR_dO39wtzYIQFV5g/viewform)

**Comment by ghost** [comment]
(他人の書き込みの修正は基本的にはやらないのですが)最初のコメントのリンク先を https://docs.google.com/forms/d/e/1FAIpQLScyfyFZbe7uZbQQzSQq78tRqtRKWXvmDRR_dO39wtzYIQFV5g/viewform に修正させてもらいました

**Comment by gurezo** [comment]
chirimen-oh.github.io にて、iseue をたてるので、close
[Chirimen Open Hardware Community slack 招待フォーム #41](https://github.com/chirimen-oh/chirimen-oh.github.io/issues/41)
