### ISSUE TITLE
CHIRIMENのアイコンについて

### ISSUE THREAD

**Issue by MSakamaki** [chirimen-oh/any-issues#11]
今のアイコンは仮

ブランディングについて調べる。

**Comment by gurezo** [comment]
了解です―決まったら、ツイッターも変更します

**Comment by dadaa** [comment]
いちおう unofficial 用だということ + https://github.com/mozilla-b2g/gaia のライセンスは apache 2.0 だということで，使えそうだとは思うものの，今後もこれをメインで使っていくのは考えどころですねー

**Comment by dadaa** [comment]
これやっぱし新しく作りたいですね

**Comment by gurezo** [comment]
2016/05/01 01:12 に @kazygumi さんがデザインしてくれたので、
そのデザインの賛否を問うので如何でしょう？
**[アイコンサンプル](https://drive.google.com/open?id=0B4V6iMhRJyKOZFFrWDZQc1JaSTA)**
何処で、賛否を判定しますかね？そのまま、採用も有りかと個人的には思っています。

ツイッター投票にしますか？Facebook グループに投票しますか？
アドバイスお待ちしております

**Comment by MSakamaki** [comment]
投票しようも比較対象がないので、そのまま採用でいいんでないかと。

**Comment by gurezo** [comment]
では、採用と云う事で！
close しちゃいますね！
@kazygumi さん、有難うございます！
