### ISSUE TITLE
CHIRIMEN-toolsの READMEリンク修正

### ISSUE THREAD

**Issue by gurezo** [chirimen-oh/any-issues#110]
TBD ... See this slideのリンク先が、MozOpenHard-monthly20151010になっています。

**Comment by ghost** [comment]
名前が問題という事でしょうか?

**Comment by gurezo** [comment]
MozOpenHardが残っている事が問題と捉えています。

**Comment by ghost** [comment]
過去の議事録ですが、改竄すべきですか?
CHIRIMEN-toolsのREADME.mdにある必要があるかという事だと、たぶんnoで、必要な情報があればchirimen.orgにでもまとめるべきだとは思います。

(あと名前の問題なら既にissueが...)

**Comment by ghost** [comment]
どちらかというと過去(MozOpenHard)のmonthly meetingの資料を回収してmeetingリポジトリに放り込んどく方がいいような気がしてきました

**Comment by ghost** [comment]
今のREADME.mdの内容なら、単にchirimen.orgのhardware specへのリンクでよさそうです。(CHIRIMEN-toolsについての説明にすべきのような気もしますが)

**Comment by gurezo** [comment]
いくつかの問題が他の要素と色々絡んで、単純なissueを立て辛い状況になっているので
時期は別途決めるにせよ、一度次回ミーティング用のアジェンダを作ります。

アジェンダの作成過程で、どの問題がどれと関連しているかを整理したいと思います。
問題やissueを簡素化したいですね。

**Comment by gurezo** [comment]
[クイックスタートリンク精査、追加 #42](https://github.com/chirimen-oh/chirimen-oh.github.io/issues/42) で、 @kudodo さんと相談の上、過去の経緯を残す事になったので、 close.

**Comment by ghost** [comment]
CHIRIMEN-toolsのREADME.mdに残す事になった、という決定がなされたのでしょうか？

**Comment by gurezo** [comment]
- Q. CHIRIMEN Open Hardware プロジェクト(コミュニティ） とは何ですか  
   ＝＞README.md の TBD ... See this slideのリンク先が、  
  　　　[MozOpenHard-monthly20151010](https://goo.gl/2W21kB) になっている  
   ＝＞「過去にこのような議論があったよ」という意味で、上記ドキュメントのリンクを  
  　　　残すという結論に至りました。

**Comment by naobsd** [comment]
本issueは「TBD ... See this slide」のリンクを残すかどうかの認識です。

MozOpenHard-monthly20151010 のドキュメントを残す事、FAQなどのリンク先とする事については異論はありませんが、そのQはCHIRIMEN-toolsのREADME.mdにはない認識です。

**Comment by ghost** [comment]
すみません、その議論に参加しておらず経緯を把握していませんし、自分で手も動かせないと思いますので、やはりこのまま(クローズ)とさせてください
