### ISSUE TITLE
replace boot logo, animation and gaia resources with CHIRIMEN logo

### ISSUE THREAD

**Issue by ghost** [chirimen-oh/any-issues#114]
* [x] boot logo (Tux) -> CHIRIMEN logo https://github.com/chirimen-oh/linux-rockchip/commit/c62811de1c1cfd30418cdf2fd16f8749c28aa873
* [x] boot animation (FxOS) -> CHIRIMEN logo animation
* [x] gaia (Foxfood) -> CHIRIMEN logo + board

**Comment by dynamis** [comment]
If you intent to change the boot logo of B2G, this bug/patch should help to understand how to do so:
Bug 1034832 - Community branding for community builds of Boot2Gecko
https://github.com/mozilla-b2g/gaia/pull/31932/files
https://bugzilla.mozilla.org/show_bug.cgi?id=1034832

**Comment by gurezo** [comment]
i had sended to Pull Request / PRを出しました
[Replacement of resource files #1](https://github.com/chirimen-oh/gaia/pull/1)

but  Error Occured by Travis CI.
しかし、下図のように Travis CI で、エラーになっています。

Reson Why Message is can't find  .travis.yml.
but fork point repository is nothing that .travis.yml .....
 .travis.ymlが無いというメッセージですが、 Fork元にも無かったので・・・・。

i had replaced resource files only, Please review & merge.
リソースファイルの差し替えだけですので、判断出来る方、レビュー＆Mergeお願いします。
<img width="945" alt="2017-01-22 1 53 41" src="https://cloud.githubusercontent.com/assets/7631567/22176219/a4e0cd0a-e048-11e6-9528-3761eb8fed1c.png">

**Comment by gurezo** [comment]
Addition / 追記
i had replaced resource files only, boot animation don't replace.  
(i don't know / undersatnd to replace method) 
リソースファイルだけなので、起動アニメーション等は
まだ手付かずです。（方法等を理解していない／分からない）

**Comment by ghost** [comment]
ペンギンロゴの置き換え、普通にやると左上からCPUの数(2)だけロゴが並ぶのですが、大きめのロゴ(480x480)を真ん中に表示するようパッチを作りました

**Comment by ghost** [comment]
リカバリの背景をCHIRIMENボードのイラストにしようかと思ったんですが、若干面倒なので(とりあえず今日は)諦めました...

画像データはこのあたり https://github.com/flingone/bootable-recovery/blob/flingone/res/images/icon_installing.png にあるのですが、単純に置き換えるだけではうまくいかない(はず)です。

**Comment by ghost** [comment]
背景を黒でなく水色 #51b5e2 にする方がよいでしょうか？

**Comment by sizuhiko** [comment]
個人的には黒のままの方が好みです

**Comment by ghost** [comment]
kernel logo置き換えました

**Comment by ghost** [comment]
bootanimationの方は素材待ちですが以下の修正でいけるはず...

- https://github.com/chirimen-oh/device-rockchip-rksdk/commit/958ab8ebd68ed8987f229a0eb20d36e9c610a81c
- https://github.com/chirimen-oh/device-chirimen/commit/46db17c7f467619aad91429b3e38eceef61017ba

(現状zipは空っぽのdummy)

**Comment by ghost** [comment]
bootanimationはこれでいいはず

- https://github.com/chirimen-oh/device-chirimen/commit/705ceb88a2c84af9d82d174810eeb8c2bdd5b4d0
- https://github.com/chirimen-oh/device-rockchip-rksdk/commit/9890fd98b2a783c0ebbbc91bd0e34983d756ec6b

**Comment by ghost** [comment]
(とりあえずrecovery backgroundの事は忘れる方向で...)

**Comment by ghost** [comment]
bootanimationはmergeした

**Comment by ghost** [comment]
gaia: https://github.com/chirimen-oh/gaia/commit/1ef258c45d7a343dff80ac814dec513aa65cbe3f
