### ISSUE TITLE
Google Group メーリングリストの削除

### ISSUE THREAD

**Issue by gurezo** [chirimen-oh/any-issues#120]
https://groups.google.com/forum/?hl=ja#!forum/chirimen-oh を削除する

メーリングリスト（旧mozOpenHard/現chirimen-oh）の作成は、W3Cを入れた議論をするため。
(今はW3Cもgithub  issuesを使用しているので気にすることはない)
→　廃止を宣言して、クローズする。

**Comment by naokisekiguchi** [comment]
さきほど終了を宣言しましたので、明日あたりに削除してcloseします。

**Comment by naokisekiguchi** [comment]
削除しました
