### ISSUE TITLE
B2G/Gecko version を FAQ に記載

### ISSUE THREAD

**Issue by dynamis** [chirimen-oh/any-issues#131]
FAQ 見ていて思いました。現在 B2G 2.5 であれば Gecko 44 ですが、それも明記してあげるとどの API までがサポートされてるか分かって良いと思います。その辺はリリースするビルドとかに書くのでも良いかもですが、OS バージョンはそうそう変えないと思えば FAQ でしょうか。

https://chirimen.org/docs/ja/FAQ.html#tocAnchor-1-1-4

**Comment by ghost** [comment]
とりあえず https://github.com/chirimen-oh/release/releases/tag/CMN2015-1_B2GOS-20160808 は B2G 2.5 (Gecko 44) OS image 〜に直してみました。
