### ISSUE TITLE
chirimen-oh organization に contributor team とか作る？

### ISSUE THREAD

**Issue by dynamis** [chirimen-oh/any-issues#132]
現在 chirimen-oh のスタッフは全員 organization で owner 権限が付与されています。この issues とかで個別の Issues を Assigneers にしたりするには何らかの形でチームに入っていて Write 権限とか持ってる必要があるかと思います。

今後片っ端から全員 Owner にするというでもまぁ何とかなるし、貢献は全てプルリクで受け付ければ問題ないという考え方もできますが、全体の Owner 権限を全員が持つのではなく staff とか contributors とか web-team みたいな該当リポジトリへの write 権限を付与する Team を作ってそこに入れていくのもありなんじゃないかと思います。

https://github.com/orgs/chirimen-oh/people
https://github.com/orgs/chirimen-oh/teams

**Comment by dynamis** [comment]
ミーティング踏まえて取り敢えず作ってみました:
- https://github.com/orgs/chirimen-oh/teams/chirimen-staff
  - 既存の Owner 権限所有者を含め、全リポジトリに Admin 権限付与済み
- https://github.com/orgs/chirimen-oh/teams/chirimen-contributor
  - 貢献者を登録し、各リポジトリに Read や Write 権限を付与するイメージ
  - note: Issues のラベルとか編集するには Write 権限が必要

**Comment by naokisekiguchi** [comment]
ひとまず、contributorに
examples
chirimen-oh.github.io 
MakerFaireTokyo2016
のwrite権限を与えました。
HAKUTOさんにMFTのコードをアップしていただきたく、contributorに招待した感じです。
contributorにはどこまで付与するのがちょうどいいですかね？
他考えられるのは
- [ ] Shields
- [ ] cording-style-tests
- [ ] gecko-dev

その他どうでしょう？

**Comment by gurezo** [comment]
今試作ケースを作っていますが、ケース用のリポジトリCases（仮名）を作るかどうか
思案中です。
作った場合は、上記に加えて頂けたらと思います。

**Comment by gurezo** [comment]
@naokisekiguchi さんへ
下記の通り、ケース用のリポジトリCasesを作ったので、追記お願いします。
https://github.com/chirimen-oh/Cases

@dadaa さんへ
slackの連携設定お願い致します。

**Comment by gurezo** [comment]
作成したので、close.
