### ISSUE TITLE
fabble リンク切れ

### ISSUE THREAD

**Issue by gurezo** [chirimen-oh/any-issues#133]
fabbleの下記ページ内で、リンク切れがあります。
http://fabble.cc/naokisekiguchi/chirimenledblink

４．CHIRIMEN上でLチカアプリを実行
GitHub: https://github.com/MozOpenHard/examples/tree/master/LEDblink
　↓
GitHub: https://github.com/chirimen-oh/examples/tree/master/LEDblink

fabbleなので、対応の方、宜しくお願い致します。

**Comment by naokisekiguchi** [comment]
リンク直しておきました。

こちらのプロジェクトは昔作ったやつでメンテしていませんでした。
以下のURLにメンテされたプロジェクトがあります。
http://fabble.cc/chirimenedu/chirimenhelloworld
