### ISSUE TITLE
コラボレーションオファーリクエストについて

### ISSUE THREAD

**Issue by gurezo** [chirimen-oh/any-issues#135]
@kskarthik さんより、コラボしないかとのオファーが来ました。
[B2G OS & Chirimen Collaboration #5](https://github.com/chirimen-oh/Support-And-FAQ/issues/5)

９月のマンスリーミーティングの議題にしたいと思います。

**Comment by kskarthik** [comment]
sorry... i couldn't understand. english please

**Comment by WhiteHawk-taka** [comment]
From @kskarthik , we got collaboration offer.
[B2G OS & Chirimen Collaboration #5](https://github.com/chirimen-oh/Support-And-FAQ/issues/5)
We want to the agenda of the September meeting on this topic.

**Comment by ghost** [comment]
@kskarthik this issue is just for internal communication (a note) for next local meeting. you can ignore this for now...

**Comment by kskarthik** [comment]
okay!

**Comment by ghost** [comment]
@gurezo 注文をつけるばかりで手を動かさず大変心苦しいのですが、議題なら https://github.com/chirimen-oh/meeting に書けばよいのではと思いました...

**Comment by gurezo** [comment]
@naobsd さん、そのとおりですね。
むやみに　issue　を作ってもしょうがないですもんね。
meeting の md ファイルに書く為のメモ的意味にもつかってしまってたので・・・。
もうちょい、工夫しますね！

アドバイスありがとうございます！

**Comment by gurezo** [comment]
コラボレーションの議論は、https://discourse.mozilla-community.org/c/b2g-os-participation で
行なう事を提案したので、こちらは、close.

Argument of collaboration is by https://discourse.mozilla-community.org/c/b2g-os-participation.
Doing was proposed, so this issue closes.
