### ISSUE TITLE
専門学校東京テクニカルカレッジの授業協力

### ISSUE THREAD

**Issue by naokisekiguchi** [chirimen-oh/any-issues#136]
11~12月に予定する専門学校東京テクニカルカレッジでのCHIRIMEN授業について、協力してくれる方、スケジュールを決めていきたい。

**Comment by naokisekiguchi** [comment]
授業のある日程は以下の通りです。
CHIRIMENでのアプリ開発経験のある方、javascriptに詳しい方にチューターとしてのご協力をお願いしたいと思います。
内容は、ブラウザ上でペアプログラミングができるような環境を用意し、チューターはリモートから参加して、学生さんの作るアプリに対して、プログラムを直接編集しながら指導を行うといったことを考えております。実際に使うシステムは現在開発中となっておりますが、授業の前に一度使い方をご説明させて頂く予定です。

協力できる方はチェックをつけてコメント頂けるでしょうか。
- [ ] 11/4 13:30〜16:40
- [ ] 11/11 13:30〜16:40
- [ ] 11/18 13:30〜16:40
- [ ] 11/25 13:30〜16:40
- [ ] 12/2 13:30〜16:40
- [ ] 12/9 13:30〜16:40

**Comment by gurezo** [comment]
@gurezo です。
直近のみ記入します。

- [x] 11/4 13:30〜16:40
- [x] 11/11 13:30〜16:40
- [x] 11/18 13:30〜16:40
- [x] 11/25 13:30〜16:40

**Comment by MSakamaki** [comment]
@naokisekiguchi 調整しました
以下日程でお手伝いできそうです。
- [x] 11/4 13:30〜16:40
- [x] 11/11 13:30〜16:40
- [x] 11/18 13:30〜16:40
- [x] 11/25 13:30〜16:40
- [x] 12/2 13:30〜16:40
- [x] 12/9 13:30〜16:40   (調整中)

**Comment by gurezo** [comment]
開発中の受講システム環境が整ったら、 @naokisekiguchi さんより、
協力者にトライアルのお願いの連絡がくる

**Comment by tadfmac** [comment]
遅い時だけで申し訳ありませんが、
- [x] 12/9 13:30〜16:40

**Comment by gurezo** [comment]
@gurezo です。
予定が変わってしまった為、再度書き込みします。
- [x] 11/4 13:30〜16:40
- [ ] ~~11/11 13:30〜16:40~~
- [x] 11/18 13:30〜16:40
- [x] 11/25 13:30〜16:40
