### ISSUE TITLE
sluckのgeneralチャネルでbot/twitterがつぶやきすぎてチャンネルとして機能不全に陥ってない？

### ISSUE THREAD

**Issue by MSakamaki** [chirimen-oh/any-issues#137]
newsチャンネルを作るか、botのつぶやく頻度を落とさないとbotでチャンネルの内容が流れる。

**Comment by gurezo** [comment]
チャンネル案内用ボット：channel-announce-bot　毎週土曜日19:00-21:00 ポスト
twitter to slack は、#general => #events へチャンネル変更
上記対応をしたので、close.
