### ISSUE TITLE
周辺デバイスページから example リポジトリへリンク

### ISSUE THREAD

**Issue by dynamis** [chirimen-oh/any-issues#139]
プルリク遅れレベルであれですが講義中に気付いたことを取り急ぎメモ:

https://chirimen.org/docs/ja/peripherals.html
https://chirimen.org/docs/en/peripherals.html

を日々メンテするのが望ましいが現実的でも無いので、増え続けるその他の example はこちらってリンクするのが良いかと思います:

https://github.com/chirimen-oh/examples

**Comment by gurezo** [comment]
https://github.com/chirimen-oh/chirimen-oh.github.io/issues/60
上記にissue60を立て、修正開始

**Comment by gurezo** [comment]
上記対応したので、close
