### ISSUE TITLE
CHRIMEN Board 発売記念イベント スタッフ募集

### ISSUE THREAD

**Issue by gurezo** [chirimen-oh/any-issues#141]
#109 の お手伝いに来て頂ける方を確認の意味も込めて募集します。

現時点で、認識している方は、 下記の通り。

開始時間から
@MSakamaki さん、 @sizuhiko さん

午後から中央大学生さんと一緒に
@dynamis さん、 @dadaa  さん、 @chikoski さんがいらっしゃると認識してます。

開始時間からお手伝い出来る方、こちらへレスをお願い致します。

**Comment by WhiteHawk-taka** [comment]
開始から行きます

**Comment by kohichi000000** [comment]
途中から途中までとかありですか？

**Comment by gurezo** [comment]
ありです！時間帯を教えてくださいませ！

**Comment by kohichi000000** [comment]
12-14時すぎあたりかなぁと。短くてすいません。
私としては、できるだけお手伝いしますが、買ったばかりの人がどういうチュートリアルほしいのか、そのうえで現時点で何が足りていないのかも知りたいです（コミュニティとしてのチュートリアル増強の参考に）。
是非、今回チュータ―やられる方からこのイベントを通じて情報を集めたい点であります～。

**Comment by gurezo** [comment]
買い物ツアー直前に参加者から軽くヒアリングできると良いかもですね！

**Comment by kohichi000000** [comment]
はい、参加者へのヒアリングもしたいですし、是非チュータ―の方には意識してほしい点です。
できれば終了後にそれをまとめたissueを立てられるといいかなと。

**Comment by dynamis** [comment]
午後には中大向けの講師として瀧田も参ります。念のため。

**Comment by gurezo** [comment]
承知しました！

**Comment by MSakamaki** [comment]
topに書いてありますが念のため。
酒巻も開始時間より参加します。

**Comment by dadaa** [comment]
ぼくも朝からいく予定です

**Comment by gurezo** [comment]
皆様、お疲れ様でした。
皆様のさぽーとに感謝です。
無事にイベントを終了したので、close
