### ISSUE TITLE
B2G OSミーティング参加

### ISSUE THREAD

**Issue by gurezo** [chirimen-oh/any-issues#143]
#135 の話に関連して、今週下記アナウンスがありました。

https://discourse.mozilla-community.org/t/b2g-os-and-gecko-annoucement-from-ari-jaaksi-david-bryant/11103

来週火曜日のB2G OSミーティング（日本時間10/05 AM01:00- ）の前に
CHIRIMEN Open Haradware コミュニティとしての意見や質疑応答内容をまとめたいと思います。
下記リンクに質問・要望・提案などを書き込みをお願いします。
https://public.etherpad-mozilla.org/p/chirimen-20161005

B2G OSミーティングの前にオンライン（スカイプ / apper.in）などで
CHIRIMEN Open Haradware コミュニティ有志と意見をまとめてから臨みたいと思います。

CHIRIMEN Open Haradware コミュニティオンラインMTG
日本時間10/04 PM21:00- 

参加できる方は、こちらに参加表明お願い致します。

**Comment by gurezo** [comment]
言い出しっぺなので、両方参加します。

**Comment by dadaa** [comment]
21 時、参加しますー

**Comment by satakagi** [comment]
参加します

**Comment by MSakamaki** [comment]
リモート(apper.in)から参加します。

**Comment by kohichi000000** [comment]
遅れるかもしれませんが参加します（リモート）

**Comment by okudako** [comment]
遅れるかもしれませんが、参加します。

**Comment by marsf** [comment]
B2G OS コミュニティでは、今週はミーティングを行わないそうです。 Telegram で、今回のミーティングを提案された Karthik さんから返事をいただきました。
CHIRIMEN コミュニティ側で意見だけでもまとめておくのが、よろしいのではないでしょうか。

**Comment by gurezo** [comment]
実施したので、close
