### ISSUE TITLE
Ubuntu環境でイメージ生成に失敗する

### ISSUE THREAD

**Issue by kazunyanya** [chirimen-oh/any-issues#144]
CHIRIMEN-toolsにて公開されているイメージ生成ツールmkupdate.sh に環境依存があるようで実行時にエラーとなる場合がありました。

ツールの公開場所
https://github.com/chirimen-oh/CHIRIMEN-tools/tree/master/rockdev-rk3066

エラーが発生する動作環境
Ubuntu 14.04 LTS desktop

問題となるコード
mkupdate.sh:
./rkImageMaker -RK30 RK30xxLoader(L)_V2.09.bin Image/update.img update.img -os_type:androidos
シェルが "( )"を含んだ文字列をファイル名として評価できずエラーとなる

対策
ファイル名 RK30xxLoader(L)_V2.09.bin をダブルコーテーションで囲めばシェル環境に依存せずエラーを回避することができます。

**Comment by dadaa** [comment]
ダブルコーテーションで囲んだものを Pull Request 送りました。
https://github.com/chirimen-oh/CHIRIMEN-tools/pull/3
ありがとうございました！
