### ISSUE TITLE
２回目以降のビルドが失敗する

### ISSUE THREAD

**Issue by kazunyanya** [chirimen-oh/any-issues#145]
2016/8/8リリースに用いられているソースコードにおいて２回目以降のビルドに失敗する事象が見つかりました。

再現方法：
$ git clone https://github.com/chirimen-oh/B2G && cd B2G
$ git checkout -b chirimen-20160808 44c92369c184431d1691773988107264c4f8d000
$ ./config.sh chirimen
$ ./build.sh
$ ./build.sh
２回目以降の build.sh でビルドが失敗する

考察：
build.sh内でソースコードにpatchを当てており、既にpatchが当たっている場合は失敗し.rejファイルが生成されるが、いくつかのファイルにおいて多重にpatchが当たってしまいビルド不能なコードとなる。

対策案：
build.shでpatch当てをおこなっているものを手動で行うか、config.shのオプションで実行できるようにするのがよいかと考えております。

**Comment by ghost** [comment]
ご報告ありがとうございます。

patch.sh については、 #65 があるので、そちらでお願いします。
(何か追記が必要であれば、日本語でも構いません)

patches/ のパッチは #88 のように整理して無くすのがよいのだと思います。
