### ISSUE TITLE
[12/3-4] Ogaki Mini Maker Faire 2016

### ISSUE THREAD

**Issue by tadfmac** [chirimen-oh/any-issues#146]
[Ogaki Mini Maker Faire 2016](http://ommf.iamas.ac.jp/) に、CHIIRMEN Open Hardware で申し込みました。

# AIリスト
- [x] 応募

応募時のフォーム記載内容は下記の通り。
https://docs.google.com/spreadsheets/d/1E_f8h7GxFKdRZ80-54V8QLyBldSeasOlkQfhPjrICKM/edit
※上記の通りMaker枠で応募
- [x] 当落結果共有 (@tadfmac) 10月中旬頃に当落結果連絡ありとのメールが来ました。

→（10/23）当選連絡来ました！！
 出展者ページに掲載されました！

- [x] 展示マニュアル展開  当選の場合、11月上旬に展開されるとのこと
　　slackの ommfチャンネルで共有DriveのURLを共有させて頂きました。ご確認のほど、よろしくお願いします。
- [x] パネル (高木さんから受け取る) @tadfmac (パネル持っていくのやめました)
- [x] テーブルクロス @tadfmac 発注done。11/30に届くので持っていく予定
- [x] レセプション申し込み 11/25 まで @申し込みdone
- [x] イベントスタッフ
  - @gurezo さん 12/3-4 終日
  - @dadaa さん 12/3
  - @WhiteHawk-takaさん 12/3-4終日
  - @tadfmac 12/3-4終日
- [x] ホテル予約 (12/3夜) 
  - @gurezo @tadfmacは 12/3の夜アパ社長カレーホテル

- [x] 展示物3 「CHIRIMENBasicShield」を関口さんから受け取る @tadfmac
- [x] 展示物4 「mini Rover」のommfへの出展可否をHAKUTOさんに確認する @kohichi000000
- [x] 「mini Rover」の出展が可能な場合、MJさんから回収 @tadfmac
- [x] 名刺 @tadfmac 名刺データ受領したので発注する（たぶん他の方は持ってるのでdone）
- [x] チラシ、シール (MJの在庫を 11/28に回収) @tadfmac
- [x] 備品の確認と準備（別途備品リスト作成）@tadfmac
- [x] 荷物の発送 (必要な場合) @tadfmac
- [x] 展示品の電源確認  @tadfmac
- [x] 作品のネームプレート @tadfmac
  → ACタップ3つ（6コ口程度）＋タコ足用で1つを3つに増やすやつ×2準備（展示品以外のPC用含め）

# 展示品

## 収集状況と運搬担当

- [x] 展示物1「くだもの触って光ったり鳴ったり」by @tadfmac):運搬担当 @tadfmac
→状況：製作中

- [x] 展示物2「kimono」CHIRIMENケース by @klaus-tonttu @gurezo :運搬担当 @gummearさん
→状況：準備OK

- [x] 展示物3「CHIRIMENBasicShield」by @naokisekiguchi:運搬担当 @tadfmac
→状況：関口さんから受け取り予定

- [x] 展示物4「mini Rover」HAKUTOさん @kohichi000000 調整中 :運搬担当 @tadfmac
→状況：高木さん確認待ち＋MJさんから回収予定

- [x] 展示物5「オブジェにアタック」@gummearさん :運搬担当 @gummearさん
→状況：製作中

- [x] 展示物6「Canzasi」CHIRIMEN用I2Cデバイス試作環境 by @tadfmac :運搬担当 @tadfmac
→状況：準備OK

### 展示物1　「くだもの触って光ったり鳴ったり」by @tadfmac
  概要：
    - タッチセンサーに繋がった果物を触ると、画面表示が変わって音が鳴ってサンタが光ります
  電源：OAタップ6小口×1（合計8小口必要。一部タコ足） @tadfmac準備done
  構成：
    - 8インチモニター+CHIRIMEN+専用シールド、マウス (以上を 2セット) 
    - ダイソーのサンタの置物改x8＋小物（装飾品）
    - センサーにつなぐ果物（現地調達予定）x 8 (スペース的に果物は4つまで。残りはミント缶で)
    - 接続するケーブル類
  必要スペース：幅80cmくらい使う

### 展示物2　「kimono」CHIRIMENケース by @klaus-tonttu @gurezo
  概要：
    - CHIRIMEN Open Hardwareコミュニティ初の完全オープンソースなアクリル製CHIRIMENケース Made In Japan!
    - 既にMade In China版もあり
  電源：不要
  構成：
    - 装着前のkimono2～3セットと、装着済みCHIRIMEN
    - 詳細はコチラへ的なシンプルな説明プレート
  必要スペース：30cm x 30cmくらい?

### 展示物3　「CHIRIMENBasicShield」by @naokisekiguchi
  概要：
    - CHIRIMEN Open Hardwareコミュニティ初の完全オープンソースなCHIRIMEN用シールド
    - 学校でのCHIRIMENを利用した授業等でも利用実績あり
  電源：不要
  構成：
    - CHIRIMENBasicShield基板（コネクタ類取り付け済み）x 1 + CHIRIMENBasicShield基板のみ x 1
    - 詳細はコチラへ的なシンプルな説明プレート
  必要スペース：20cm x 20cmくらい?

### 展示物4　「mini Rover」HAKUTOさん @kohichi000000 調整中
  概要：
    - Maker Faire Tokyo 2016向けに、HAKTOさんが制作したWeb経由で操作可能なリモコンRover
  構成：
    - mini Rover
    - 設定用PCと、mini Roverを接続するためのモニタ（8インチ）※机の上に並べる必要なし
  電源：充電用に電源1＋AC電源口1つ必要。
  必要スペース：机の上に必要なのは、20cm x 20cmくらい。

### 展示物5　「オブジェにアタック」@gummearさん  (スペース中?)
  概要：
    - タッチセンサ内容のオブジェにミニドローン又は  
      ピコピコパハンマーを接触させ、画面表示が変わって音が鳴らす。
  構成：
    - 7インチモニター+CHIRIMEN、マウス、キーボード
    - センサーにつなぐオブジェ（暫定1~4）
    - ピコピコパハンマー又はそれに変わるもの
    - 接続するケーブル類
  電源：OAタップ4小口×1必要 @gummear準備done
 必要スペース：20cm x 20cm見込み。

### 展示物6　「Canzasi」CHIRIMEN用I2Cデバイス試作環境 by @tadfmac  (スペース小)
  概要：
    - Arduinoを使って自由にI2Cデバイスを試作する環境。
    - OSHWA UID: JP000001 !
  構成：
    - Canzasi:Prot v0.2 x 2
    - Arduino UNO Rev.3 + Canzasi:Wrtr v0.1 x 1
    - 詳細はコチラへ的なシンプルな説明プレート
  電源：不要
  必要スペース：30cm x 30cmくらい

# 備品リスト（展示品以外）

- [x] OAタップ 5～6個口2つ @tadfmac (11/28納品予定？)
- [x] ラジオペンチ、ニッパ、ピンセット (11/28に収集) @tadfmac
- [x] ポータブルスピーカー、4chミキサー、3.5mmミニジャックステレオケーブル 5-6本
- [x] チラシ、シール @tadfmac (11/28回収予定)
- [x] テーブルクロス @tadfmac (11/30納品予定)
- [x] 作品のネームプレート @tadfmac 
- [x] イーゼル  @gurezo
- [x] はんだゴテセット @gurezo
- [x] ゴミ処理用ビニール袋 @gurezo
- [x] 養生テープ x 4 @gurezo
- [x] ガムテープ x 2 @gurezo
- [x] 結束バンド @gurezo
- [x] ドライバセット @gurezo
- [x] 精密ドライバセット @gurezo

**Comment by kohichi000000** [comment]
@tadfmac: パネルを印刷したものが私の手元にありましたので、適当なタイミングで渡します。

**Comment by tadfmac** [comment]
ホテルについて、下記連絡を頂きましたので、念のため展開します。

# ホテルご案内2通目

Ogaki Mini Maker Faire 2016
ご出展のみなさま

こちらはOgaki Mini Maker Faire 2016実行委員会事務局です。

本日、Ogaki Mini Maker Faire 2016会場に隣接する
宿泊所のご案内をお送りしましたが、
１２月３日（土）のご宿泊については満室になりましたので
お知らせします。
同日のご宿泊をお考えの方は、近隣ホテルを
ご利用くださいますようお願いいたします。

なお、１２月２日（金）宿泊分については、
ひきつづきご予約可能です。
ご希望の方は次の電話までご連絡ください。

ワークショップ２４
　電話：0584-83-7001　受付時間8:00～18:00
　※「Ogaki Mini Maker Faire 2016の宿泊申込」とお伝えください。

# ホテルご案内1通目

Ogaki Mini Maker Faire 2016
ご出展のみなさま

こちらはOgaki Mini Maker Faire 2016事務局です。
宿泊施設に関するご連絡をいたします。

大垣での宿泊については、市内各所のホテルに加えて、
Ogaki Mini Maker Faire 2016会場に隣接する宿泊施設がございます。
（１泊税込み１人料金 Lタイプ1700円、Mタイプ700円）
こちらをご希望される場合には、先着順で受け付けを行いますので、
次の電話番号までお申し込みください。

ワークショップ２４
　電話：0584-83-7001　受付時間8:00～18:00
　※「Ogaki Mini Maker Faire 2016の宿泊申込」とお伝えください。

■ご留意事項
　・ご予約は電話のみで承ります。
　・ご応募が宿泊可能定員を超えた場合には、受付を終了いたします。
  ・車でご来場される場合には、ソフトピアジャパン・センタービル地下駐車場をご利用ください（有料）。

■施設概要
　施設名：ワークショップ２４　７階　ソピアキャビン
　住所：岐阜県大垣市今宿6-52-18
　部屋数：全50室（すべてシングル）
　　　　　うち完全個室10室（１泊１人1700円・税込み）
　　　　　　  簡易個室40室（１泊１人 700円・税込み）
　施設紹介webページ：http://www.softopia.info/syukuhaku/
  施設の場所：https://goo.gl/maps/eMpsihu8H9P2
　※この施設はOgaki Mini Maker Faire 2016実行委員会メンバーが運営しています。

■前夜祭のご案内
　開催前日（12/2・金）には、前夜祭としてトークセッションを開催します。
　金曜日からご宿泊の方はぜひご参加ください。

　　～Ogaki Mini Maker Faire 2016 前夜祭トークセッション～

　　　著名なSF作家であると同時に黎明期から日本における
　　　メイカームーブメントに参加してこられた野尻抱介先生を
　　　お迎えして、IAMAS小林茂教授と共に今までを振り返りつつ
　　　多様性と可能性を探ります。

　　　日時：12月2日（金） 19:00 - 21:00
　　　会場：ソフトピアジャパン センタービル 1F セミナーホール
　　　　　　（Ogaki Mini Maker Faire 2016会場の１階です）
　　　入場料：無料

以上、よろしくお願いいたします。

**Comment by tadfmac** [comment]
メール見落としており、展開が遅れ申し訳ありません。
12/3の夜、レセプションが開催されるようですが、申し込みの期限が本日のようです。
以下、メールコピペ

### メール
Ogaki Mini Maker Faire2016実行委員会事務局からのお知らせです。
12月18日にメールでご案内したとおり、
レセプションの参加申込みの締切が明日11月25日(金) 15時までとなっております。
ご参加される方はメールにてお申込みください。

 日時：12月3日（土）18時30分から20時00分まで
 会場：ソフトピアジャパンセンター3Fソピアホール（ホワイエ）
 参加料：一人2,000円（当日会場にてグループ毎にお支払いください）
 申込み方法：エントリーフォーム：https://goo.gl/forms/Q2ZLboEvtrdJfadO2に必要事項を入力いただき、メールでお申込みください。
既にお申し込み済の方は再送の必要はございません。

Ogaki Mini Maker Faire 2016実行委員会事務局

**Comment by tadfmac** [comment]
11/28のミーティング向けに、issueを書き換えました。

**Comment by WhiteHawk-taka** [comment]
12/3,4参加します。
3日の早朝に岐阜に着き、4日の晩に @gurezo さんと帰路につく予定です。
当日CHIRIMENキット一式持っていくので何かあれば言ってください。

**Comment by tadfmac** [comment]
11/28 打ち合わせアジェンダ：
- 当日参加者の連絡先交換
- 出展マニュアルの確認のお願い
- プレゼンの紹介

以上、赤塚さんいるうちに

- 展示品の簡単な共有
- 備品の確認及び回収
- 疑問点等あれば共有
- テーブルレイアウト（時間があれば）

**Comment by WhiteHawk-taka** [comment]
作品：よくある温度をツイートするあれ(CHIRIMENでは初？)を持ち込みますのでスペースがありましたら乗せてください

**Comment by tadfmac** [comment]
@WhiteHawk-taka さん
おお、ありがとうございます！
スペースは現場で調整しましょう！いかようにでもなると思いますので、ぜひ展示をお願いします。
作品の名前が決まっていたら、今からネームプレートを作成しますので、教えてください！
よろしくお願いします。

**Comment by tadfmac** [comment]
Ogaki Mini Maker Faire 2016
出展者のみなさま

こちらはOgaki Mini Maker Faire 2016実行委員会事務局です。
本イベントの開幕も、いよいよ今週末に迫って参りました。
出展準備も佳境を迎えていることと存じますが、
どうぞお体に気を付けてお過ごしください。
会場内は暖房を入れていますが、１階での展示の方
（ブース番号１～30）は、出入り口からの外気が入りやすい
環境でございますので、暖かめの恰好でブースに詰めていただくと
よいかもしれません。

さて、事務局より２点お知らせがございます。

■前夜祭トークセッションのご案内
　12月2日（金）19:00-21:00に、OMMF2016の会場である
　ソフトピアジャパンセンタービル 1F セミナーホールにて
　前夜祭トークセッションを開催いたします。

　ゲストにSF作家の野尻抱介氏をお招きし、OMMF2016総合
　ディレクターの小林茂と共に、娯楽イベントではないMaker Faireの
　側面にスポットを当て、Maker ムーブメントのこれまでと、
　今後の展望を語ります。

　２日（金）より会場入りされる方、また前日入り可能な方は
　どうぞお誘いあわせのうえお越しください。
　http://ommf.iamas.ac.jp/talksession

■安全確認のお願い
　本イベントでの事故防止を図るため、12/3及び4の両日、
　係員が各ブースにお邪魔して、展示状況の確認を実施させて
　いただく予定です。
　具体的には、
　・申請したワット数以内で電気をご使用いただいているか
　・発熱物がある場合、可燃物に近接して設置していないか
　・発火や爆発するような危険物はないか
　といった点を確認いたします。
　イベントの安全確保のため、お手数ですがどうぞご協力
　くださいますようお願いします。

それではスタッフ一同、皆さまを会場でお待ちしています。

**Comment by tadfmac** [comment]
ご協力いただいた皆様、ありがとうございました。
ommf無事（?ではなかった部分もありますが）終了しましたので、一旦Closeいたします。
