### ISSUE TITLE
おさわり会イベント (4月30日) 

### ISSUE THREAD

**Issue by MSakamaki** [chirimen-oh/any-issues#15]
### タスク
- [x] @naokisekiguchi  さんと具材の調整 => @naokisekiguchi OKのお返事
- [x] チューター兼参加者の整理
### 関連issues
- #14 
- #13

**Comment by MSakamaki** [comment]
@naokisekiguchi さん
当日お貸しいただけるデバイス一覧ってどこかにありましたっけ？

**Comment by naokisekiguchi** [comment]
こちらに記載しております。
https://github.com/chirimen-org/any-issues/wiki/Available-devices-for-Events

**Comment by WhiteHawk-taka** [comment]
イベントのetherpadです
https://public.etherpad-mozilla.org/p/chirimenday-20160430
