### ISSUE TITLE
I2CSlaveDevice.write16() がwrite8と同じ動作になる

### ISSUE THREAD

**Issue by tadfmac** [chirimen-oh/any-issues#152]
2箇所の実装によるもののようです。

- [x] 1. [Polyfill](https://github.com/club-wot/WebGPIO)の[write16()](https://github.com/club-wot/WebGPIO/blob/draft-20160125/src/WebI2C/interfaces/I2CSlaveDevice/I2CSlaveDevice.js#L126)の中でwrite8()と同じ関数を呼び出している

　[関連 issue](https://github.com/club-wot/WebGPIO/issues/6)

- [x] 2. Geckoに実装されている`I2cService.WriteWord()`[(I2cService.h)](https://github.com/chirimen-oh/gecko-dev/blob/b2g44_v2_5-chirimen/dom/i2c/I2cService.h#L43)[(I2cService.cpp)](https://github.com/chirimen-oh/gecko-dev/blob/b2g44_v2_5-chirimen/dom/i2c/I2cService.cpp#L97)の第３引数の型が`uint8_t`となっており、2byteのデータが渡せない

@naobsd さんに2. の修正（上記`I2cService.WtiteWord()`の第３引数を`uint16_t`に変更）ビルドをご協力頂き、1. も併せて修正することでwrite16()が利用できるようになる（Polyfillを利用したアプリから`I2CSlaveDevice.write16()`を呼び出すことで対象のテストデバイスまでwriteコマンドでレジスタ1byte+データ2byte計3byte書き込める）ことを確認させて頂きました。@naobsd さんご協力ありがとうございます。

**Comment by tadfmac** [comment]
先に 2. からPull Requestを発行させていただく予定でおります。
https://github.com/chirimen-oh/gecko-dev/pull/3
こちらに登録させていただきました。

**Comment by tadfmac** [comment]
そして、Polyfill側の修正についてもPRを発行させていただきました。
https://github.com/club-wot/WebGPIO/pull/21

※ビルド方法がわからず、@gurezo さんに多大なるご協力を頂きました。 この場を借りて御礼申し上げます。

**Comment by MSakamaki** [comment]
> club-wot/WebGPIO#21

こちら確認してマージしておきました、最新に適用済みです。

**Comment by tadfmac** [comment]
@MSakamaki さん、Polyfill側修正反映いただき、ありがとうございます！ 
本issueは、polyfill側とgecko側の2箇所直す必要がありますので、下記PR反映まで本issueはOpenのままとさせてください。
https://github.com/chirimen-oh/gecko-dev/pull/3
よろしくお願いします。

**Comment by MSakamaki** [comment]
@tacoyaky  すいません間違えてこちらもcloseしちゃってました、了解です。
