### ISSUE TITLE
Prepare a youtube channel for sharing CHIRIMEN demo

### ISSUE THREAD

**Issue by naokisekiguchi** [chirimen-oh/any-issues#155]
これまでに行ったCHIRIMENのデモなどの映像を蓄積するページが欲しいです。

例えばyoutubeチャンネルを作るなど。

**Comment by gurezo** [comment]
参考情報
CHIRIMEN Open Hardware 試作ケース作成風景１
https://youtu.be/fkBaA8vkx9o

CHIRIMEN Open Hardware 試作ケース作成風景２
https://youtu.be/58fjvvnk_jc

CHIRIMEN Open Hardware 試作ケース作成風景３
https://youtu.be/5RQlMZqj2KI

CHIRIMEN Open Hardware 試作ケース作成風景４
https://youtu.be/ednT7vi35CE

**Comment by gurezo** [comment]
chirimen.open.hardware@gmail.comアカウントでyoutubeのチャンネルを作ろうと思います。

**Comment by gurezo** [comment]
chirimen.open.hardware@gmail.comアカウントでyoutubeのチャンネルを作りました。
https://www.youtube.com/channel/UCd7PtdviaJeHfMMFeszx06A

**Comment by gurezo** [comment]
作ったので、close
