### ISSUE TITLE
CHIRIMEN周辺機器動作確認リストの作成

### ISSUE THREAD

**Issue by tadfmac** [chirimen-oh/any-issues#158]
タイトルの通りです。
下記に動作確認できたデバイスを皆で追記する（コメントを追記するのではなく、本欄を直接編集・表に行を追加する）形で情報収集したいです。
→適当なタイミングで[このページ](https://chirimen.org/docs/ja/peripherals.html)に追記していく。

# USB WIFIドングル

|メーカー名|機種名|動作|確認者|記載日|備考(動作状況等)|
|:---|:----|:--:|:---|---:|:---|
|ReUdo|[RE-UW100](https://www.amazon.co.jp/%E5%B0%8F%E5%9E%8BUSB-Wireless-LAN-Adapter%E3%80%81802-11b-2%E5%80%8B%E3%82%BB%E3%83%83%E3%83%88/dp/B00DMUB3HE)|◯|@tadfmac|2016.12.7|特に問題なく動作|
|PLANEX|[GW-USNANO2A](https://www.planex.co.jp/products/gw-usnano2a/)|◯|@tadfmac|2016.12.7|特に問題なく動作|
|BUFFALO|[WLI-UC-GNM](http://buffalo.jp/product/wireless-lan/client/wli-uc-gnm/)|×|@tadfmac|2016.12.8|認識しない|
|IO-DATA|[WN-G150UMK](http://www.iodata.jp/product/network/adp/wn-g150um/)|◯|@tadfmac|2016.12.8|特に問題なく動作|
|ELECOM|[WDC-150SU2MBK](http://www2.elecom.co.jp/network/wireless-lan/adapter/wdc-150su2m/)|×|@gurezo|2016.12.8|認識しない|
|Realtek|RTL8188CUS-GR|◯|@sizuhiko|2016.12.15|特に問題なく動作。無刻印のためチップの型番だけ入れています。[この製品](http://www.ebay.ca/itm/Mini-150Mbps-150M-USB-WiFi-Wireless-Adapter-Network-LAN-Card-802-11n-g-b-2-4GHz-/171324064404)と見た目は同じです|
|ELECOM/Logotic|[LAN-WH300NU2](http://www.logitec.co.jp/products/wlan/lanwh300nu2/)|◯|@sizuhiko|2016.12.15|特に問題なく動作|

# USBハブ

|メーカー名|機種名|動作|確認者|記載日|備考(動作状況等)|
|:---|:----|:--:|:---|---:|:---|
|エレコム|[U2H-PP3BBK](http://www2.elecom.co.jp/cable/usb-hub/u2h-pp3b/)|◯|@tadfmac|2016.12.7|マウス＋WIFIドングルで動作確認。直挿しタイプのためCHIRIMENをケース等で底上げしないと物理的にCHIRIMENが傾く|
|エレコム|[U2H-TZ410SBK](http://www2.elecom.co.jp/cable/usb-hub/u2h-tz410s/)|◯|@kotakagi|2016.12.8|マウス+WIFIドングルで動作確認|
|GREEN HOUSE|[GH-UH204SBK L000/1550](http://www.green-house.co.jp/products/pc/supply/usbhub/standard/gh-uh204sb/)|◯|@tadfmac|2016.12.8|マウス+WIFIドングルで動作確認|
|NDHCi|[回転式 縦付可能 3ポート USB 2.0 ハブ](https://www.amazon.co.jp/gp/product/B00MSQPN3I/ref=oh_aui_detailpage_o08_s00?ie=UTF8&psc=1)|◯|@naokisekiguchi|2016.12.8|マウス+WIFIドングルで動作確認|
|iBUFFALO|[BSH4U25BK](http://buffalo.jp/product/peripheral/usb-hub/bsh4u25/)|△|@naokisekiguchi|2016.12.8|WiFiドングルでRTL8188CUS搭載のバルク品（CHIRIMENでの動作は確認済）が動作せず。GW-USNANO2Aは動作確認|
|エレコム|[U2H-SN4BRD](http://www2.elecom.co.jp/products/U2H-SN4BRD.html)|◯|@WhiteHawk-taka|2016.12.14|マウス+WIFIドングルで動作確認|
|ELECOM|[U2H-Z10SBK](http://www2.elecom.co.jp/cable/usb-hub/u2h-z10s/)|◯|@sizuhiko|2016.12.15|マウス+WIFIドングルで動作確認|
|エレコム|[U2H-SN4NBBK](http://www2.elecom.co.jp/products/U2H-SN4NBBK.html)|◯|@gurezo|2016.12.16|マウス+WIFIドングルで動作確認|

# HDMIモニター

|メーカー名|機種名|動作|確認者|記載日|備考(動作状況等)|
|:---|:----|:--:|:---|---:|:---|
|Diginnos（ドスパラ）|[DG-NP09D](http://www.dospara.co.jp/5shopping/detail_parts.php?ic=437191&lf=0)|◯|@tadfmac|2016.12.7|古いCHIRIMENで720P出力の場合、本モニタは拡大機能が無いので中央に小さく写る。1080Pの場合は見切れ等発生せず問題なし|
|BENQ|ET-0019N|◯|@tadfmac|2016.12.8|1080p対応モニタ。とくに問題なし|
|aitendo|[SET-6802V2-L070](http://www.aitendo.com/product/11853)|×|@gurezo|2016.12.11|上下左右見切れあり<br />[TV接続時に画面が切れる #1](https://github.com/chirimen-oh/Support-And-FAQ/issues/1)<br />上記対応で、解決するかを確認したい|
|cocopar|[s5-800](https://www.amazon.co.jp/gp/product/B00WGVL4R4/ref=oh_aui_detailpage_o04_s00?ie=UTF8&psc=1)|△|@kotakagi|2016.12.14|上下左右見切れあり。解像度設定の問題（800x480）のため、下記対応で解決することは確認済み。<br />[TV接続時に画面が切れる #1](https://github.com/chirimen-oh/Support-And-FAQ/issues/1)<br />もちろん、タッチパネルはそのままでは不能|
|Gechic|[On-Lap 1101H](http://amzn.asia/ce8RirX)|◯|@sizuhiko|2016.12.14|とくに問題なし|
|BENQ|BENQ G2400W ET-0009-B (古いのでリンク割愛)|△|@tadfmac|2016.12.14|1920x1200サイズのモニタ。縦が1200に引き伸ばされるため、縦方向だけ拡大されてしまう。|
|seetec?|[不明](https://www.amazon.co.jp/Koolertron-%E3%82%AB%E3%83%A1%E3%83%A9%E3%83%88%E3%83%83%E3%83%97%E3%83%95%E3%82%A3%E3%83%BC%E3%83%AB%E3%83%89%E3%83%A2%E3%83%8B%E3%82%BF-Sunshine-Shoemount-Camera-Top/dp/B009YT071A/)|◯|@WhiteHawk-taka|2016.12.14|譲り受けたものなためこれと思うものをピックアップ。動作に問題はなし|
|iiyama|[proLite GB2888UHSU](http://www.iiyama.co.jp/products/lcd/28/GB2888UHSU/)|◯|@sizuhiko|2016.12.15|とくに問題なし|
|PLILOW<br />TFT LCD<br />COLOR<br />MONITOR|[7inch TFT LCD COLOR MONITOR](http://robotbase.en.alibaba.com/product/1219795105-217010523/7_inch_Color_TFT_LCD_Monitor.html)|◯|@gurezo|2016.12.16|とくに問題なし|

~~# USBマウス （要る？）→要らない~~

# USB 電源アダプタ

|メーカー名|機種名|動作|確認者|記載日|備考(動作状況等)|
|:---|:----|:--:|:---|---:|:---|
|PLANEX|[PL-WUCHG03](https://www.planex.co.jp/product/bannou/pl-wuchg03/)|◯|@tadfmac|2016.12.14|とくに問題なし(2つ口のうち1つにCHIIRMENを接続。1つ空けた状態で使用)|
|Apple|[Apple 5W USB電源アダプタ MD810LL/A【A1385】](http://www.apple.com/jp/shop/product/MD810LL/A/apple-5w-usb%E9%9B%BB%E6%BA%90%E3%82%A2%E3%83%80%E3%83%97%E3%82%BF)|△|@tadfmac|2016.12.14|有線マウス+モニタ接続では問題なし。WIFIアダプタやハブ接続によりリセット等発生する場合があり不安定な印象|
|Apple|[Apple 12W USB電源アダプタ](http://www.apple.com/jp/shop/product/MD836LL/A/apple-12w-usb%E9%9B%BB%E6%BA%90%E3%82%A2%E3%83%80%E3%83%97%E3%82%BF?fnode=85&fs=f%3Dadapter%26fh%3D459d%252B45b0)|◯|@tadfmac|2016.12.14|有線マウス+モニタ+ハブ+WIFI接続+アプリ動作で問題なし|
|トキワ電気|[TJ-SAX001AR](http://tokizo.net/item.html)|◯|@tadfmac|2016.12.14|有線マウス+モニタ+ハブ+WIFI接続+アプリ動作で問題なし|
|au|[共通ACアダプタ03](http://auonlineshop.kddi.com/disp/CSfLastGoodsPage_001.jsp?GOODS_NO=2428)|◯|@tadfmac|2016.12.14|有線マウス+モニタ+ハブ+WIFI接続+アプリ動作で問題なし(ommfで問題あったのと同じやつなんだけど再現せず。現場電源環境が悪かった?)|
|HTC|[TC P900-US](https://www.amazon.com/Original-HTC-TC-P900-Charger/dp/B00R6WMPY4)|◯|@tadfmac|2016.12.14|有線マウス+モニタ+ハブ+WIFI接続+アプリ動作で問題なし|
|au|[共通ACアダプタ05](http://auonlineshop.kddi.com/disp/CSfLastGoodsPage_001.jsp?GOODS_NO=4528)|◯|@WhiteHawk-taka|2016.12.14|有線マウス+モニタ+ハブ+WIFI接続+アプリ動作で問題なし|
|ELECOM|[U2H-TZ420SBK](http://www2.elecom.co.jp/cable/usb-hub/u2h-tz420s/)|x|@gurezo|2016.12.16|WIFIアダプタやハブ接続によりリセット等発生する場合があり不安定な印象|

**Comment by kohichi000000** [comment]
進め方ですが
「動作確認できた＝動いた」
ではなく、動かないなら「どう動かないか」も書いていってもらったほうがいいと思う。
そういう意味ではつないでみたものをどんどん書いてもらうのがいいと思う。
別の言い方をすると「動いた（動作確認できた）」にもいろいろなレベルがあると思うのでそれも考慮。
（今、備考に書いていただいている通り）

**Comment by tadfmac** [comment]
動かなかった場合も書くということですね。
了解です。
ちょっと今から用事で(移動中)すぐできないので夜やります
→動作状況欄追加　基本は◯か×で。
→備考欄に状況を補足お願いします。

**Comment by gurezo** [comment]
製品のリンクも貼っておいた方が、後々楽かもしれません。

**Comment by tadfmac** [comment]
@gurezo あざーす！（モニター等の記載もおねがいします！）

**Comment by naokisekiguchi** [comment]
一部の組み合わせで動作せず、というのはどう書いたらいいでしょう？△にしちゃいましたが。
英語化するときに悩みそう。

**Comment by tadfmac** [comment]
@naokisekiguchi さん
ありがとうございます。
動作制限などの事象が発生したときの書き方は、一旦は書く人の主観で書いていただいていいと思います。今回の事例は△でいいかと。そのうちたくさん事例が集まってきたときに、良い書き方の収斂方法も見えてくると思ってますので

**Comment by tadfmac** [comment]
USB電源アダプタを忘れていましたので、追加します。
こちらは、どういった環境で動いた、動かなかったという報告をお願いします。

> ommfで、 @gurezo さん、 @WhiteHawk-taka さんがハマった状況など、普通に発生しうる問題だと思いますので、起動ちゃんとできなかった（リセット繰り返す）などの報告も重要です。

ご協力宜しくお願いします。

@kohichi000000 さん
あのRoverで使った充電器もUSB電源アダプタのところに書いて欲しい

**Comment by sizuhiko** [comment]
手元にあるものはすべて入力しました

**Comment by gurezo** [comment]
追記しました。

**Comment by tadfmac** [comment]
皆様、ご協力ありがとうございます！
大体必要な情報が集まりましたので、一旦集約のうえ、webへ反映させていただきます。

**Comment by tadfmac** [comment]
webに反映後closeします

**Comment by tadfmac** [comment]
https://github.com/chirimen-oh/chirimen-oh.github.io/pull/69

**Comment by tadfmac** [comment]
一旦Closeします。今後は wiki を更新ねがいます。
https://github.com/chirimen-oh/chirimen-oh.github.io/wiki/peripherals(ja)
https://github.com/chirimen-oh/chirimen-oh.github.io/wiki/peripherals(en)
