### ISSUE TITLE
CHIRIMENのGPIO/I2Cへのデバイス/パーツ接続動作確認リストの作成

### ISSUE THREAD

**Issue by tadfmac** [chirimen-oh/any-issues#159]
タイトルの通りです。
下記に動作確認できたデバイス/パーツ/を皆で追記する（コメントを追記するのではなく、本欄を直接編集・表に行を追加する）形で情報収集したいです。
→適当なタイミングで[このページ](https://chirimen.org/docs/ja/peripherals.html)に追記していく。

- 「製品名」欄には、製品名と、入手先のリンクを貼ってください。
- 「動作」欄は、期待動作＝「◯」、動かなかった＝「×」、一部制限あり＝「△」
- 「回路」「サンプルコード」欄には下記形式でURLを貼ってください。GPIOやI2Cにつなぐモノの多くはPartsです。繋げば動くというデバイスとは違うものが多く含まれますので、どのような回路でつないだのか？、その回路をもとに、どのようなコードで動かしたのか？がセットで情報収集できていないと意味がありません。
- 動作確認のベースを合わせるため、動作確認はファームウエア[CMN2015-1_B2GOS-20160808](https://github.com/chirimen-oh/release/releases/tag/CMN2015-1_B2GOS-20160808
) で実施をお願いします。もし上記以外のファームで動作させた場合には、内容がわかるよう補足いただけたら幸いです。

"[回路](URL)"
"[サンプルコード](URL)"

# CHIRIMENのGPIOポートに直接接続（回路形成）しWeb GPIO API 経由で制御させたデバイス/パーツの確認結果

|製品名|回路|サンプルコード|動作|確認者|記載日|備考(動作状況等)|
|:---|:---|:----------|:--:|:---|---:|:---|
|LED |[回路](http://fabble.cc/chirimenedu/chirimenhelloworld)|[サンプルコード](https://github.com/chirimen-oh/examples/tree/master/LEDblink)|◯|@tadfmac|2016.12.16|特に問題なく動作。LEDについては5mm砲弾型、3mm砲弾型、表面実装問わずGPIOポートに200Ω〜1KΩ程度の抵抗（LEDのカラーや種類により発光に適した抵抗値が異なる）を経由してアノードを接続、カソードをGNDに接続することで動作可能。アプリ起動前から微妙に光ってしまうので初期Pulldownポートに接続推奨|
|タクトスイッチ(モーメンタリ) |[回路](https://fabble.cc/chirimenedu/chirimenpushbutton)|[サンプルコード](https://github.com/chirimen-oh/examples/tree/master/button)|◯|@tadfmac|2016.12.16|特に問題なく動作。モーメンタリタイプのタクトスイッチであれば、形状問わず接続、同様動作が可能。今回動作確認したサンプルと同じ動作を実施するためには、Pullupポートに接続する必要がある|

# CHIRIMENのI2Cポートに直接接続（回路形成）しWeb I2C API 経由で制御させたデバイス/パーツの確認結果

|製品名|回路|サンプルコード|動作|確認者|記載日|備考(動作状況等)|
|:---|:---|:----------|:--:|:---|---:|:---|
|[MCP4018](http://akizukidenshi.com/catalog/g/gI-07610/)|[回路](http://qiita.com/tadfmac/items/04257bfe982ba0f050bb)|[サンプルコード](http://qiita.com/tadfmac/items/04257bfe982ba0f050bb)|◯|@tadfmac|2016.12.12|writeのみ確認。30msインターバルでの書き込みも問題なく動作 (5時間連続動作を確認)|
|[PAJ7620(Grove Gesture V1.0)](http://wiki.seeed.cc/Grove-Gesture_v1.0/)|[回路](http://fabble.cc/tadfmac/chirimen-i2c-paj7620-gesture)|[サンプルコード](https://github.com/chirimen-oh/examples/tree/master/i2c-PAJ7620-Gesture)|◯|@tadfmac|2016.12.14|基本的なジェスチャー判定のみ実装。期待動作を確認 ※VDD 3.3V接続|
|[Grove I2C OLED Display](https://www.seeedstudio.com/grove-oled-display-12864-p-781.html)|[回路(WIP)]()|[サンプルコード](https://github.com/tadfmac/examples/tree/oled_display/i2c-PAJ7620-Gesture)|△|@tadfmac|2016.12.14|キャラクター書き込みサンプルを作成。1画面書き換えにwrite8()版で15秒程度、write16版でも10秒弱かかるため実用的なパフォーマンスは得られていない ※VDD 3.3V接続|
|[SRF02 (超音波センサー)](http://akizukidenshi.com/catalog/g/gM-06685/)|[回路](http://fabble.cc/chirimenedu/chirimeni2csensor)|[サンプルコード](https://github.com/chirimen-oh/examples/tree/master/i2c-SRF02)|◯|@tadfmac|2016.12.16|特に問題なく期待動作 ※VDD 5V接続|
|[ADT7410 (温度センサー)](http://akizukidenshi.com/catalog/g/gM-06675/)|[回路](http://fabble.cc/chirimenedu/chirimeni2csensor)|[サンプルコード](https://github.com/chirimen-oh/examples/tree/master/i2c-ADT7410)|◯|@tadfmac|2016.12.16|特に問題なく期待動作(少し温度の変化への追従が遅いようだが、ADT7410側の仕様とおもわれる) ※VDD 3.3V接続|
|[S11059-02DT (デジタルカラーセンサー)](http://akizukidenshi.com/catalog/g/gK-08316/)|[回路](http://fabble.cc/chirimenedu/chirimeni2csensor)|[サンプルコード](https://github.com/chirimen-oh/examples/tree/master/i2c-S11059)|◯|@tadfmac|2016.12.16|特に問題なく期待動作 ※VDD 3.3V接続|
|[Grove I2C デジタル光センサー](https://www.switch-science.com/catalog/1174/)|[回路](http://fabble.cc/chirimenedu/chirimeni2csensor)|[サンプルコード](https://github.com/chirimen-oh/examples/tree/master/i2c-grove-light)|◯|@tadfmac|2016.12.16|特に問題なく期待動作 ※VDD 3.3V接続|
|[PCA9685 (PWM/サーボ ドライバー)](https://www.switch-science.com/catalog/961/)|[回路](https://fabble.cc/chirimenedu/chirimenservo)|[サンプルコード](https://github.com/chirimen-oh/examples/tree/master/i2c-PCA9685)|◯|@tadfmac|2016.12.16|[SG90 (サーボモーター)](http://akizukidenshi.com/catalog/g/gM-08761/)を接続して動作。特に問題なく期待動作 ※VDD 5V接続、V+端子にも5V供給が必要。詳細は回路URL参照|
|[Grove I2C 三軸加速度センサ ADXL345搭載](https://www.switch-science.com/catalog/972/)|[回路](https://fabble.cc/chirimenedu/chirimeni2csensor-v2)|[サンプルコード](https://github.com/chirimen-oh/examples/tree/master/i2c-grove-accelerometer)|◯|@tadfmac|2016.12.16|[特に問題なく期待動作 ※VDD 3.3V接続|

# PWMやADCドライバ等を経由して接続したデバイス/パーツの確認結果

|製品名|回路|サンプルコード|動作|確認者|記載日|備考(動作状況等)|
|:---|:---|:----------|:--:|:---|---:|:---|
|[SG90 (サーボモーター)](http://akizukidenshi.com/catalog/g/gM-08761/)|[回路](https://fabble.cc/chirimenedu/chirimenservo)|[サンプルコード](https://github.com/chirimen-oh/examples/tree/master/i2c-PCA9685)|◯|@tadfmac|2016.12.16|[I2Cポートに接続したPCA9685 (PWM/サーボ ドライバー)](https://www.switch-science.com/catalog/961/)経由で動作確認。特に問題なく期待動作|

**Comment by tadfmac** [comment]
定例会で依頼させて頂きましたが、確認用のファームウエアバージョンは下記でお願いします。
・[CMN2015-1_B2GOS-20160808](https://github.com/chirimen-oh/release/releases/tag/CMN2015-1_B2GOS-20160808)
ただし、様々な事情により別のファームウエアでの情報の場合には、その旨わかるよう備考欄に補足をお願いします。

**Comment by sizuhiko** [comment]
確認の実装方法としては、WebGPIOを使った場合という事にしますか？

**Comment by tadfmac** [comment]
@sizuhiko さん
ありがとうございます。
はい。ご認識の通りです。

- Web GPIO APIを利用したデバイス/パーツの確認結果
- Web I2C API を利用したデバイス/パーツの確認結果

に記載を修正しました。

**Comment by dynamis** [comment]
いろんなセンサーが使えるよ感がないとツライので、動くのは自明なんですけど GPIO デバイスと ADC 経由でのアナログセンサー類を一気に書き足すとかすると良いと思いますが如何でしょう？

具体的には (CHIRIMEN じゃないやつ用のからで恐縮ですが) こういった感じのセンサー類を (これよりももっと) 一気にリストに追加するイメージ:
https://github.com/mozilla-japan/gecko-embedded/wiki/Grove
なお、上記ページに記載のある Grove モジュールは私が私物で持ってるので Mozilla オフィスに来て頂くときなどにテスト頂けます。

**Comment by tadfmac** [comment]
今回本issueで作成したいのは「動作確認リスト」なので、動作確認できていないパーツをリストに加えるのは、個人的には、賛成できません。

GrooveモジュールのMozillaオフィスでの貸し出しにつきましては、ご提案頂きありがとうございます。
CHIRIMENで使えるモジュールを共有する目的で本issueを立てさせていただきましたので、Mozillaオフィスにお邪魔して、接続できそうなデバイス（I2Cインタフェースのものや、GPIO接続で単純なHIGH/LOWを返すだけのもの）については動作確認させて頂けたらと思います。

**Comment by dynamis** [comment]
勿論、未確認の状態で確認で追加するのではなく、間違いなく動くだろうものの動作をさっと確認して追加するという意図です。

アナログセンサ via ADC については直接じゃないのでちょっと反則かもしれませんが、「ADC xxxxx 経由で接続を確認したデバイス」などというかたちの表も追加して書いておくと、いろんなセンサーが使える感が出て良いと考えています。PWM サーボとかも同様です。

別 Issue にすべきだったかも知れませんが、ある程度のセンサーのリストが無いと何も繋がらない何も出来ない印象になってしまうのを何とかしたいからです。

**Comment by tadfmac** [comment]
了解いたしました。貴重なご意見ありがとうございます。

ADCやPWMドライバをブリッジして、経由で動作確認したパーツも本レコードに記載する方向で良いと思います。(先ほど、PWMドライバ経由でのサーボ動作が確認できましたので追記させていただきました)

ただし、ブリッジ経由であること、動作確認した回路等も含めて情報集約しないと、あまり意味のない情報になってしまいます。
杞憂かもしれませんが、アナログ用センサーをGPIOに直結しようというような話が散見されていますので、こうした誤まった用法（センサー本来の機能が得られる「接続」とはいえない）が広まる原因を生まないような注意が必要だと思っています。

**Comment by tadfmac** [comment]
念のため、本日時点で [chirimen-oh/examples](https://github.com/chirimen-oh/examples)に登録されている全てのデバイスが[最新ファーム(CMN2015-1_B2GOS-20160808)](https://github.com/chirimen-oh/release/releases/tag/CMN2015-1_B2GOS-20160808)で動作確認できましたので更新しておきました。引き続き、追加デバイスについての情報更新をお願いします。

**Comment by tadfmac** [comment]
こちらに作成予定です。
https://github.com/chirimen-oh/chirimen-oh.github.io/wiki/parts(ja)

**Comment by tadfmac** [comment]
https://github.com/chirimen-oh/chirimen-oh.github.io/pull/69

**Comment by tadfmac** [comment]
一旦Closeします。今後は wiki を更新ねがいます。
https://github.com/chirimen-oh/chirimen-oh.github.io/wiki/parts(ja)
https://github.com/chirimen-oh/chirimen-oh.github.io/wiki/parts(en)
