### ISSUE TITLE
CHIRIMENの次期量産販売について

### ISSUE THREAD

**Issue by naokisekiguchi** [chirimen-oh/any-issues#160]
現在、スイッチサイエンスさんで販売して頂いているCHIRIMEN（[Echigo Rev.1](https://www.switch-science.com/catalog/2833/)）については在庫が限られてしまうため、CHIRIMENの次期量産販売について検討していきたい。

まずは一度関係者でF2Fミーティングを設けて状況を整理して戦略を立てて行きたいです。

**Comment by gurezo** [comment]
already sold out at January 9th.

**Comment by gurezo** [comment]
#193 に引き継いだので、close
