### ISSUE TITLE
Web I2C API 品質改善版の本線への反映について

### ISSUE THREAD

**Issue by tadfmac** [chirimen-oh/any-issues#164]
現在、CHIRIMENで利用可能なWeb I2C APIについて、例えばwrite8()呼び出し時にSlaveAddressが異なる等、実はNative側では明らかなエラーが返っている時もWebアプリ側にはエラーが返却されない等の課題があります。
B2G側の実装が足りないことにより、Polyfill側も対応できていない状況で、B2GとPolyfillを併せて改善を試みている最中です。

[一時的な中間成果登録場所](https://github.com/tadfmac/chirimen-expr)

これらの実デバイスを用いた評価とコード整理後にしかるべきfork元リポジトリにPull Requestを実施予定ですが、今回の修正により Web I2C APIの PolyfillとB2G側imageを同時に更新すしないと動作しなくなっています。(Native側のAPI、I2CManager.write()等のパラメータを変更しているためIF互換性がなくなっており、Native側とPolyfill側を同時に更新する必要があります)

また、exampleに登録された各I2Cモジュール向けのサンプル実装についてですが、こちらは従来のままでも新いPoyfill＋imageで動作するものの、新しい実装に合わせた方がよりシンプルな記載が可能になると考えています。このため、exampleについても修正版を作成する必要があると思います。

こうした事情から、いきなり現在の最新正式リリース版バイナリと置き換えるのは差し控えたいと考えています。
ある程度の期間、新しいimage/Polyfill/exampleをβ版としてリリースし、このコミュニティの方々に利用頂くことでの評価期間を経て正式版に差し替えたい考えです。

以上を踏まえ、次回コミュニティミーティングで下記についてご意見をいただけたら幸いです。

1. β版バイナリのリリース方法 ([release](https://github.com/chirimen-oh/release/releases)への登録方法。β版を分けたい)
2. polyfillへのPRとbranchの作成について @MSakamaki さんと相談させていただきたい
3. exampleへのPRとbranchの作成について

### AI

- [x] [chirimen-oh/gecko-dev](https://github.com/chirimen-oh/gecko-dev)へのPull Request
   https://github.com/chirimen-oh/gecko-dev/pull/4

- [x] βリリース
   https://github.com/chirimen-oh/release/releases/tag/CMN2015-1_B2GOS-20170120

- [x] [club-wot/WebGPIO](https://github.com/club-wot/WebGPIO)へのPull Request  (上記調整結果による)
   https://github.com/club-wot/WebGPIO/pull/26

- [x] [chirimen-oh/examples](https://github.com/chirimen-oh/examples)のブランチ作成
- [x] [chirimen-oh/examples](https://github.com/chirimen-oh/examples)へ新リリース向けの改善
- [x] image正式リリース

**Comment by gurezo** [comment]
beta版を[CMN2015-1_B2GOS-20170120](https://github.com/chirimen-oh/release/releases/tag/CMN2015-1_B2GOS-20170120) に配置

**Comment by tadfmac** [comment]
次回コミュニティミーティングで https://github.com/chirimen-oh/release/releases/tag/CMN2015-1_B2GOS-20170120 の正式版化についてご確認いただきたく、よろしくお願いします。

**Comment by tadfmac** [comment]
当初のタスクからexamlesの改善が残っている状況ですが、既存のexampleでも問題はないため、exampleの改善については別issueを立てて対応することにし、本issueは一旦Closeします。
