### ISSUE TITLE
3/1 release

### ISSUE THREAD

**Issue by tadfmac** [chirimen-oh/any-issues#167]
AI 

3/1といいつつ 2/24リリース予定。

- [x] リリースの箱準備
   → https://github.com/chirimen-oh/release/releases/tag/CMN2015-1_B2GOS-20170301 @WhiteHawk-taka さん、あざーす！
- [x] https://github.com/chirimen-oh/gecko-dev/pull/4
   →マージ完了 @gurezo さん、あざーす！
- [x] examplesの bowser install を一時的に封じる対応 (新リリースで古いPolyfillは使えなくなるため) @tadfmac
   → 下記の通り対応
    - chirimen-oh/examplesに`forCMN2015-1_B2GOS-20170301` branchを作成
    - このリリースではbower installは不要である旨各サンプルのreadme.mdに記載
    - index.htmlの`webi2c.js`/`webgpio.js`のpathを`./js/`に変更。これにより誤って`bower install`してもpre-install済みpolyfillが上書きされない
    - 各exampleの`./js/`に[#24,#25修正のPullrequest](https://github.com/club-wot/WebGPIO/pull/26)反映済みPolyfillを配置

- [x] スタートアップアニメーション差し替え #114 
  → @naobsd さん、宜しくお願いします。 2/23完了希望
- [x] https://github.com/club-wot/WebGPIO/pull/26
  → マージまでにはしばらくかかりそうなので、3/1リリース時に同梱する @tadfmac
- [x] ビルド @tadfmac
  → @naobsd さんにやっていただきました！ありがとうございます。
- [x] リリースに放り込む @tadfmac
  → @naobsd さんにやっていただきました！ありがとうございます。
- [x] pre-releaseのチェック外す @tadfmac

以上やったら本issue close

**Comment by gurezo** [comment]
close
