### ISSUE TITLE
Set Team Icon for Slack

### ISSUE THREAD

**Issue by dynamis** [chirimen-oh/any-issues#169]
primary owner @dadaa owner @oshimaryo admin @gunmaer のどなたか、Team の Settings 画面
https://chirimen-oh.slack.com/admin/settings
の Team Icon 設定で
https://github.com/chirimen-oh/chirimen-oh.github.io/blob/master/img/browser_300.png
辺りを設定頂けないでしょうか。

Slack Team いっぱい入ってるとアイコン設定が無いと不便なので。。。

**Comment by dadaa** [comment]
done
