### ISSUE TITLE
720Pなど、他の解像度への対応

### ISSUE THREAD

**Issue by gurezo** [chirimen-oh/any-issues#178]
- [ ] In order to be able to read letters etc even when connected with a monitor with a small resolution, it is possible to output CHIRIMEN with multiple resolutions.

参考リンク
https://github.com/chirimen-oh/Support-And-FAQ/issues/1

**Comment by ghost** [comment]
~~こちらは
#83 HDMI - more display resolution support
の話ではなく、overscanの話でしょうか？~~

**Comment by ghost** [comment]
https://public.etherpad-mozilla.org/p/chirimen-20170330 に続きが書いてあるのですね。

> 　今回、モニターが壊れまくったけど、もちろんそれはモニターの問題も大きいけど、
> 　CHIRIMEN側がモニターに1080Pを要求するから選択肢が少なくなり、結果として例のモニターに、
> 　という流れもある。というか、安いモニターが使えない。
> 
> 　720Pだと随分安いモニターもあって選択肢も広がるように思える

**Comment by ghost** [comment]
しかし、720pでも映りますよね？何が問題なのでしょうか？

課題があるとは思っていますが、本issueについて具体的にどのような点が問題でどのようにしたいのか、読み取れませんでした。

**Comment by ghost** [comment]
本件はframe bufferを1920x1080から1280x720にする、という事で了解しました。

**Comment by gurezo** [comment]
6/18 release @WhiteHawk-taka

**Comment by ghost** [comment]
https://github.com/chirimen-oh/linux-rockchip/commit/f7c32cbe6cfd499423b31d98d4fa89a2b82ee6d1 frame bufferを1280x720にしました

**Comment by gurezo** [comment]
対応していただいたので、close
