### ISSUE TITLE
Prepare a template for any-issues

### ISSUE THREAD

**Issue by MSakamaki** [chirimen-oh/any-issues#179]
problem that the request (definition of done) is unknown and can not be issues closed

 + [x] about preparing a template message  (look for the draft)
 + [x] impliments of github template

**Comment by gurezo** [comment]
i had maked a ISSUE_TEMPLATE.md.
[ISSUE_TEMPLATE.md](https://github.com/chirimen-oh/any-issues/blob/master/ISSUE_TEMPLATE.md)

please review this ISSUE_TEMPLATE.md.

**Comment by gurezo** [comment]
26 April #186 already merged.
