### ISSUE TITLE
firmware flashing guide for Mac OS X/macOS Using CHIRIMEN-tools(rkflashtool, rkunpack) 

### ISSUE THREAD

**Issue by gurezo** [chirimen-oh/any-issues#182]
## issue purpose
- guide making for CHIRIMEN-tools(rkflashtool, rkunpack) 

## Close conditions
- [ ] guide making for CHIRIMEN-tools(rkflashtool, rkunpack) .
- [ ] guide release to [chirimen.org](http://chirimen.org).

**Comment by ghost** [comment]
#59 の続き？

**Comment by gurezo** [comment]
> #59 の続き？

はい。ですが、現状 #149 で、間に合っている事や
#192 の状況なので、リソースを別に注力するためにclose
