### ISSUE TITLE
Implement WebGPIO polyfill for node backend

### ISSUE THREAD

**Issue by dynamis** [chirimen-oh/any-issues#188]
## Overview Description (Goal of this issue)
We want WebGPIO polyfill for node backend to make WebGPIO testable/usable on other devices.
This make API consideration easy and fast. Also, many other devices including production embedded devices can share same code and ecosystem.

* [CHIRIMEN] - [current WebGPIO polyfill] - [browser applications]
* [node.js] - [gpio module] - [new WebGPIO polyfill] - [node applications]
* [node.js] - [gpio module] - [local gpio server] - (web socket?) - [another WebGPIO polyfill for Firefox] - [browser applications]

## Action Itemc (Requirements to close this issue)
- [ ] select node version (6.x or later?)
- [ ] select node module for GPIO
  - https://www.npmjs.com/package/gpio ?
- [ ] implement WebGPIO polyfill on node
- [ ] implement WebGPIO polyfill on normal Firefox with local node backend

see also: #189

**Comment by naokisekiguchi** [comment]
I implemented a prototype of web gpio polyfill for node backend.
https://github.com/naokisekiguchi/nodegpio

**Comment by dynamis** [comment]
create repo with new implementation: #195

**Comment by dynamis** [comment]
DONE by tadfmac: https://github.com/chirimen-oh/chirimen-raspi3
