### ISSUE TITLE
CHIRIMEN Open Hardware Terms of Use For License

### ISSUE THREAD

**Issue by gurezo** [chirimen-oh/any-issues#190]
## Overview Description (Goal of this issue)
Mozilla Japan Company change to WebDINO Japan.
so that, CHIRIMEN Open Hardware License will be need to change.

## Action Items (Requirements to close this issue)
- [ ] License
- [ ] Who has a trademark?

## Steps to Reproduce (only for bugs):
1. 
2. 
3.

**Comment by dynamis** [comment]
I believe this issue have already solved wtih https://github.com/chirimen-oh/chirimen-oh.github.io/issues/77
