### ISSUE TITLE
WebIDE (will be) removed

### ISSUE THREAD

**Issue by gurezo** [chirimen-oh/any-issues#192]
## Overview Description (Goal of this issue)
Mozilla had announced to change that add-on to WebExtension.
Because of its influence, these operations cann't be performed.
- Display project tree and Edit area (Firefox ver55.0.0 or later)
- Install WebApps (Firefox ver55.0.3 or later)

## Related information
https://bugzilla.mozilla.org/show_bug.cgi?id=1314811
https://bugzilla.mozilla.org/show_bug.cgi?id=1391641

## Action Items (Requirements to close this issue)
- [ ] We Will be need to choice any item at **[next meeting](https://github.com/chirimen-oh/meeting/blob/master/2017/meeting-2017.09.30.md).**
  - [ ] Will you continue to use B2G OS in the future?
  - [ ] Will you continue to use WebIDE in the future?

## Steps to Reproduce (only for bugs):
1. 
2. 
3.

**Comment by gurezo** [comment]
if you want to use WebIDE, you'll be install Firefox ver54 ESR.

**Comment by dynamis** [comment]
I suggest
* to introduce Firefox ESR 52 (with no auto version up config)
  * http://ftp.mozilla.org/pub/firefox/releases/52.4.0esr/
* not to continue to commit for b2g (or successor)

**Comment by dynamis** [comment]
Community agreed to do so on the meeting on 2017.09.30
We'll need to update documents to introduce FxESR 52 (will file another issue). -> close
