### ISSUE TITLE
Prepare CHIRIMEN distribution image for RPi3 (based on Raspbian)

### ISSUE THREAD

**Issue by dynamis** [chirimen-oh/any-issues#197]
## Overview Description (Goal of this issue)
Create CHIRIMEN sd boot image file for RPi3 based on Raspbian Stretch with desktop
https://www.raspberrypi.org/downloads/raspbian/

Raspbian don't have trademark and need not too be sensitive for it's branding (boot animation etc).
Some packages may not re-distribution (not sure) and safe to remove them:
http://karaage.hatenadiary.jp/entry/2017/06/20/073000
* Java
* Wolfram
* minecraft pi

## Action Items (Requirements to close this issue)
- [x] add chirimen specific files
- [x] remove unnecessary packages including license un-clear ones
- [x] create sd image file

**Comment by kohichi000000** [comment]
upload img as follows:
https://drive.google.com/open?id=0B4k_ph7hQTADVy1lOVZ0UlNwdHc

**Comment by gurezo** [comment]
@kohichi000000 this links is problem.
Sometimes the download fails, and more It is 1 KB when unpacking.
OS is Windows10 Insider Preview

Strangely, masOS Sierra had succussed.
What 's happened???

**Comment by gurezo** [comment]
I had replaced zip and img files to dropbox.
foloowing this url.
https://www.dropbox.com/sh/bxdud4hidy3xbnv/AABI-EKkBZevAbxaq_t79M-ja?dl=0

**Comment by kohichi000000** [comment]
thx

**Comment by tadfmac** [comment]
release note for previous (Uploaded by @kohichi000000 ) OS image : (I'm sorry, in japanese)

Version Name : 2017/09/27-2

Installation : 
- このimageはRaspberry Pi 3でのみ動作検証を行なっており、本VersionはRaspberry Pi 3以外のボードはサポートしておりません。
- 8GByte以上のmicroSDカード(Class 10以上) へ書き込んでください。
- このimageは圧縮されています。初回起動後 `sudo raspi-config` から、`7 Advanced Options`→`A1 Expand Filesystem` を必ず実施してください。実施後、再起動してください。

trouble shooting:
- ~/Desktop/gc/GPIO などのexamples実行時、'wss://localhost:33330/' へ接続できないエラーが発生する場合があります。このエラーに遭遇した場合には、一度ブラウザ画面から`https://localhost:33330` へアクセス後、セキュリティエラー画面から例外許可を行なってください。
- 長時間examplesを連続実行していると熱暴走のような症状が発生することがあります。ヒートシンクを装着してください

known issues:
- Chromium browserにチュートリアルがまだ含まれておりません
- パフォーマンスのチューニングが不完全です

**Comment by WhiteHawk-taka** [comment]
release note for previous (Uploaded by @kohichi000000 ) OS image : (I'm sorry, in English)

Version Name : 2017/09/27-2

Installation :

- This image has only been verified to work on RaspberryPi 3, So this version has no support for other boards.
- Please write the image to a microSD card (higher than Class 10) that is larger than 8GByte.
- This image is compressed. After initial startup, you must do `sudo raspi-config` then `7 Advanced Options` → `A1 Expand Filesystem` . After that, you need to reboot.

trouble shooting:

- When executing examples such as ~/Desktop/gc/GPIO, a can not connect to 'wss://localhost:33330/' error may occur. If you encounter this error, go to `https://localhost:33330` from the browser, please allow the security exception from the security error screen.
- Problems such as thermal runaway may occur if examples are continuously executed for a long time. Please attach a heat sink.

known issues:

- The chromium browser does not yet include tutorial.
- Performance tuning is not complete.
