### ISSUE TITLE
github名も統一しますか？

### ISSUE THREAD

**Issue by gurezo** [chirimen-oh/any-issues#20]
### @naobsd さんから 下記指摘が。
- 「githubはchirimen-ohじゃないんですね...」
### github名も統一しますか？
- @MSakamaki さん、github名って、chirimen-org-> chirimen-ohって出来るんでしたっけ？  
  Organizationsって、やった事ないので分からないのですが・・・。
- 4/18 に@dynamis さんと @dadaa さんで、[http://chirimen.org/ ](http://chirimen.org/) で  
  まとまったと認識してるのですが・・・・。  
  話を蒸し返してる感があるので、皆様の意見を下さいませ。
- [http://chirimen-oh.org/ ](http://chirimen-oh.org/) になると良いのかな？  
  slack にもポストしましたが、現時点（4/24 22:15時点）では上記ドメイン名でも可能な模様

**Comment by MSakamaki** [comment]
chirimen-ohは文字の長さでohと記憶してたので、ちゃんと名前がつけれる所はChirimenOpenhardにしたほうが良いと考えてます
ドメインとかも含めて一度話した方がいいかもですね。

**Comment by gurezo** [comment]
### 名前も微妙に違いが・・・・。
- CHIRIMEN Open Hardware（投票時）
- CHIRIMEN Open Hard（うろ覚え）

---

**※どこかで議論しましょう！**
文字数の制約もありますね・・・・。

**Comment by satakagi** [comment]
CHIRIMEN Open Hardは時々MozOpenHardとの混同から使われていることがあるのかもしれませんが、CHIRIMEN Open Hardwareが正ですよね？

**Comment by dadaa** [comment]
CHIRIMEN Open Hardware が正ですー

**Comment by satakagi** [comment]
それと、ドメイン名は、
＞＞4/18 に@dynamis さんと @dadaa さんで、http://chirimen.org/  でまとまった
で合意できていると思っています。今別の名前に変えることを議論するのは確かに時機を逸していると思います。
名称がCHIRIMEN Open Hardwareでもそのドメイン名がchirimen.orgというのは　すごく違和感があるというほどでもない（特にOpen Hardwareの部分は固有名詞とは見えないため）ので、CHIRIMENがドメイン名として取得できているならば（食べ物のちりめんとかでそれを使いたいという人たちが今のところいなかった）、それでも悪くはないと思いますがいかがでしょう。

**Comment by gurezo** [comment]
では、まとめとして
正式名称：CHIRIMEN Open Hardware
github名：http://chirimen.org/

上記で問題なければ、この議論をcloseしようとお思います。
如何でしょう？

**Comment by satakagi** [comment]
私は賛成です^^ 
あ、http://chirimen.org/
は、ドメイン（ホームページアドレス）ですね。
github名については、chirimen-orgですね。　確かにちょっと気にはなるのかもですが、たしかchirimenがとられていたんでしたっけ？

**Comment by gurezo** [comment]
@MSakamaki さん、
@dadaa さん、
@naokisekiguchi さん、
@naobsd さん、如何でしょうか？？？

**Comment by dadaa** [comment]
ひとまず現状を：
ホームページURL: http://chirimen.org/
Slack: chirimen_oh
twitter: chirimen_oh
GitHub: chirimen-org
(これから Facebook url: chirimen_oh?)

**Comment by gurezo** [comment]
そのまとめで良いと思います。

**Comment by dadaa** [comment]
しかし，たしかにこうならべると，chirimen_oh の方が統一感はありますね〜

**Comment by gurezo** [comment]
それなので、issueを立てちゃいました。
http://chirimen-oh.org/

なまじ、上記ドメイン名が取得できる状況だけに・・・・。
本当に混ぜ返し／蒸し返して、すみません。

**Comment by dadaa** [comment]
なんか，ドメインは chirimen.org がステキな感じしますけど，他利用サービスは chirimen_oh 統一が気持ちよい感じがしました

**Comment by gurezo** [comment]
自分が気になるのは、仮に http://chirimen-oh.org/ 変更したとして、
今皆さんが作業されている労力が、ドメイン名変更でまた労力が発生する事のが
容易に想像出来るので・・・。

**Comment by dadaa** [comment]
あ，いえ，URL は http://chirimen.org で，GitHub のグループを chirimen_oh にするって感じです．

**Comment by dadaa** [comment]
すると，
ホームページ: http://chirimen.org/
Slack: chirimen_oh
twitter: chirimen_oh
GitHub: chirimen_oh
Facebook url: chirimen_oh

**Comment by dadaa** [comment]
どうかしら？

**Comment by gurezo** [comment]
あ、そうゆう意味ですね！
理解しました！
で、あればこれで議論をまとめましょうか？
@MSakamaki さん、
@satakagi  さん、
@naokisekiguchi さん、
@naobsd さん、宜しいでしょうか？？？

**Comment by gurezo** [comment]
@dadaa さんのまとめで、closeしようと思います。

ホームページ: http://chirimen.org/
Slack: chirimen_oh
twitter: chirimen_oh
GitHub: chirimen_oh
Facebook url: chirimen_oh

**Comment by dadaa** [comment]
みなさん，どうでしょう？

**Comment by gurezo** [comment]
では、異論なさそうなので、close します

**Comment by ghost** [comment]
出遅れてすみません、私は元々githubの名前が気になっただけでchirimen.orgを変える話はしてませんでしたので、結論に基本的には異論はないです。
強いて一つ言うならば、ホスト名にunderscoreは使えないので、サービスによってはunderscoreが使えない場面が出てくる可能性があるかもと思います。
