### ISSUE TITLE
CHIRIMEN on Raspi3 Touch and Try Events

### ISSUE THREAD

**Issue by gurezo** [chirimen-oh/any-issues#200]
## Overview Description (Goal of this issue)
#189 , #188 , #197 CHIRIMEN on Raspi 3 environment Touch and Try, Feedback Events

## Action Items (Requirements to close this issue)
- [x] event page edit
 - [CHIRIMEN on Raspi3おさわり会](https://connpass.com/event/68440/edit/)
- [x] schedule setting.
- [x] event contents setting.
- [x] entry setting.
- [x] place network setting.
- [x] tutorial upload
- [x] image upload
- [x] devices preparation
- [x] SD environment setting

## Steps to Reproduce (only for bugs):
1. 
2. 
3.

**Comment by tadfmac** [comment]
Tutorials are here : 
Hello World
https://qiita.com/tadfmac/items/82817476615fdc7394b3

チュートリアル 1. GPIO編
https://qiita.com/tadfmac/items/ebd01cfe46e30de70f3d

チュートリアル 2. I2C　基本編（ADT7410温度センサー）
https://qiita.com/tadfmac/items/36d5467f79b6fd3114fb

チュートリアル 3. I2C　応用編（その他のセンサー）
https://qiita.com/tadfmac/items/b17d8c6a35b31c495a36

チュートリアル 4. 最終回
https://qiita.com/tadfmac/items/d627f8d2fec3c5f8711b

**Comment by tadfmac** [comment]
Temporary image file using for this event is here:
https://drive.google.com/open?id=0B4k_ph7hQTADcVVlYzR6a0lqX3M

Please see the following installation document as:
https://gist.github.com/tadfmac/527b31a463df0c9de8c30a598872344d

**Comment by tadfmac** [comment]
Thank you for participating in this event.
The event is over, so this thread will close.
