### ISSUE TITLE
Submit to use "Powered by Raspberry Pi" mark

### ISSUE THREAD

**Issue by dynamis** [chirimen-oh/any-issues#201]
## Overview Description (Goal of this issue)
We need to submit to this form to use "Powered by Raspberry Pi" mark within "CHIRIMNE on/for Raspberry Pi":
https://www.raspberrypi.org/trademark-rules/powered-raspberry-pi/

## Action Items (Requirements to close this issue)
- [x] submit!
- [x] check reply.

**Comment by dynamis** [comment]
@kohichi000000 is asking about logo usage including this (set him as assignees)

**Comment by kohichi000000** [comment]
I have submitted!

**Comment by kohichi000000** [comment]
I have got the reply.
We need NOT "Powered by Raspberry Pi logo" BUT "link to the Raspberry Pi Foundation". 
(We cannot use the logo for digital or online products.)
Raspberry Pi Foundation's Reply is as follows:

> Thank you for your interest in our “Powered by Raspberry Pi” program.
> We have reviewed your application but on this occasion will not approve this for use of the "Powered by Raspberry Pi" logo.
> The "Powered by Raspberry Pi" is intended for use on industrial or retail products that have a Raspberry Pi built into them.
> ·         For digital and online products a link to the Raspberry Pi Foundation website is sufficient. You can find the guidelines for using our logo here: https://www.raspberrypi.org/trademark-rules/
> You can find out more about the "Powered by Raspberry Pi" program here: https://www.raspberrypi.org/blog/powered-by-raspberry-pi/
>

**Comment by tadfmac** [comment]
I already removed `Powered by Raspberry Pi l` mark from wallpaper at release 2017/10/17.
