### ISSUE TITLE
Maker Faire Tokyo 2019 スタッフ募集

### ISSUE THREAD

**Issue by gurezo** [chirimen-oh/any-issues#205]
### お手伝い可能な方は、下記フォーマットに追記
- [ ] 08/03(土) AM
- [ ] 08/03(土) PM
- [ ] 08/04(日) AM
- [ ] 08/04(日) PM

**Comment by gurezo** [comment]
@gurezo 日曜日は朝から入ります！
- [ ] 08/03(土) AM
- [ ] 08/03(土) PM
- [x] 08/04(日) AM
- [x] 08/04(日) PM

**Comment by kou029w** [comment]
たぶん両日手伝えると思います〜

- [x] 08/03(土) AM
- [x] 08/03(土) PM
- [x] 08/04(日) AM
- [x] 08/04(日) PM

**Comment by sizuhiko** [comment]
作品持っていきますー

- [x] 08/03(土) AM
- [x] 08/03(土) PM
- [x] 08/04(日) AM
- [x] 08/04(日) PM

**Comment by gurezo** [comment]
イベントが終了したので、close
