### ISSUE TITLE
ハードウェアのリポジトリがない

### ISSUE THREAD

**Issue by satakagi** [chirimen-oh/any-issues#24]

**Comment by dadaa** [comment]
https://github.com/chirimen-org/any-issues/issues/10
ここになるかと思います．

**Comment by satakagi** [comment]
releaseリポジトリの作成とディレクトリ構成を早急にしないとですね。

**Comment by ghost** [comment]
#10 で進行中なのでしたら、こちらはcloseできるのではないでしょうか？(こちらはこちらでやる事が別にあるのでしたら、すみません)
