### ISSUE TITLE
CHIRIMENホーム―ページ(http://chirimen.org/)のリポジトリの使い方が・仕組みの説明がない。またわかったとしてもwindowsユーザには相当ハードルが高い感じ

### ISSUE THREAD

**Issue by satakagi** [chirimen-oh/any-issues#26]

**Comment by satakagi** [comment]
http://jekyllrb-ja.github.io/docs/windows/
これは参考になるかも。ただ基本的にはwindowsはサポート外

**Comment by MSakamaki** [comment]
自分もWindows使っていますが、VertualBox + UbuntuにJekillを入れてプレビュー環境を整えていました。(修正とgithubへのpushもvmから)
あとは[Docker](https://hub.docker.com/r/grahamc/jekyll/)を利用すると言う手も取れると思います。

**Comment by MSakamaki** [comment]
以下で管理、こっちはclose
https://github.com/chirimen-oh/chirimen-oh.github.io/issues/9
