### ISSUE TITLE
examplesはfabbleと被っている

### ISSUE THREAD

**Issue by satakagi** [chirimen-oh/any-issues#28]

**Comment by naokisekiguchi** [comment]
fabbleでは電子部品の使い方やインストール方法をなど含むドキュメントを記載して、サンプルコードはexamplesレポジトリを参照しようという理解です。
fabble -> ドキュメント
examples -> ソースコード

**Comment by naokisekiguchi** [comment]
以下のissueで説明文を整理する
#23
