### ISSUE TITLE
Decide examples license

### ISSUE THREAD

**Issue by naokisekiguchi** [chirimen-oh/any-issues#31]
examplesのライセンスを決めてREADME.mdに記載しておくべきかと。
MIT Licenseでしょうか。

**Comment by dadaa** [comment]
mozilla では基本的に Apache 2.0 ないし MPL 2.0 を使ってます．
ただ examples に関しては MIT でも問題なかろうかと思います．

**Comment by naokisekiguchi** [comment]
@MSakamaki 、その他みなさまどう思いますか？
それと、MITだとするとコピーライトはどんなのがいいでしょうかね。
Copyright (c) 2016 CHIRIMEN Open Hardware
Licensed under the MIT License
とか？

**Comment by MSakamaki** [comment]
:+1:

**Comment by naokisekiguchi** [comment]
MITのライセンスファイルなど置いときました。
