### ISSUE TITLE
Rearrange slack channel

### ISSUE THREAD

**Issue by naokisekiguchi** [chirimen-oh/any-issues#32]
slackのchannelがわかりにくいので整理して説明を記載

**Comment by ghost** [comment]
#eventsはイベント関連の情報が流れる、でいいとして、#scheduleは？
#webは？projectのwebどーしましょって話はissuesでやってますよね？
#devと#portingの使い分けは？たぶんWebAPIを使うアプリを作る話と、CHIRIMENの上でB2Gを動かす話は、分けた方がよいとは思うのですが(WebAPIを実装する話はどっちだろう...)

**Comment by kohichi000000** [comment]
できれば、ホームページやgithubのリポジトリとの整合もわかるようにしたい

**Comment by dadaa** [comment]
チャネルの説明を加える

**Comment by ghost** [comment]
(#33 に貼ってあったのをこっちにも)
https://docs.google.com/spreadsheets/d/1ibBG4Ee_COF6rRQWu1-qVpC9zTGwcScTRnXU4xjAxHU/edit?usp=sharing

**Comment by ghost** [comment]
#scheduleと#webは削除していただきました

**Comment by naokisekiguchi** [comment]
不足していた(?)webapiとhardwareチャンネルを加えて、各チャンネルのpurposeに説明を追加しました。どなたか確認、必要なら修正してくださいー。

上のgoogle docみると#devはアプリ開発とかでしたね。
#dev は#dev-appとかの名前にしたほうがわかりやすい気がしますが、いかがでしょう？
（チャンネル作成者か管理者しか名前は変更できない）

**Comment by ghost** [comment]
issueのラベル、platformをportingに変更しちゃいました(slackの#portingにあわせました)

**Comment by gurezo** [comment]
説明文を @naokisekiguchi さんに書いて頂いたのと #105 で対応したので、close
