### ISSUE TITLE
Labeling issues

### ISSUE THREAD

**Issue by ghost** [chirimen-oh/any-issues#33]
ラベルをつけて何の話題か区別したい
- イベント関連 (events)
- コミュニティ運営関連 (?)
- B2G移植関連 (?)
- WebAPI関連 (?)

など

**Comment by ghost** [comment]
#23 でちょっとラベルの話が出てるのに気が付きました。any-issuesで全て管理するのであれば
- github リポジトリに対応したラベル

も必要ですね。

**Comment by kohichi000000** [comment]
ラベル付けするために必要そうなアイテムの一覧＋対応に関する表を作ってみました。適当に書き込んでみてください。
https://docs.google.com/spreadsheets/d/1ibBG4Ee_COF6rRQWu1-qVpC9zTGwcScTRnXU4xjAxHU/edit?usp=sharing
