### ISSUE TITLE
CHIRIMENs with pin socket are desired for event

### ISSUE THREAD

**Issue by naokisekiguchi** [chirimen-oh/any-issues#34]
イベント用にピンソケットのついたCHIRIMENが欲しい。
スルーホール用ワイヤーは高い、壊れやすい。
個人的にはメスピンソケットが好み。

**Comment by tadfmac** [comment]
メスピンソケットに+1
理由：
- ブレッドボードと、オスオスのジャンパーワイヤーで接続できる
- CHIRIMENは現状ArduinoやRaspiのように広く認知されたPIN配置ではないのでブレッドボードを経由した試作を前提にするのが現実的

**Comment by ghost** [comment]
#92 と重複しているのですが、こちらcloseしてよいでしょうか？

**Comment by ghost** [comment]
続きは #92 でお願いいたします
