### ISSUE TITLE
(7/30) NodeBots Day 2016 for Tokyo

### ISSUE THREAD

**Issue by ega1979** [chirimen-oh/any-issues#36]
#7/30にMozilla Japanさんで「NodeBots Day」を開催したいと思います。

J5などJavaScriptを使って作って騒ごうというハッカソン的＆もくもく会な感じにしたいですが、このイベントにchirimenもJoinできないかなと考えていますが、どうでしょう？

**Comment by MSakamaki** [comment]
@ega1979 さん
これって申込やもろもろの期日って何時迄ですか？
余裕があるなら次回MTGのテーマにするのが良いかなと思います。

**Comment by ega1979** [comment]
@MSakamaki さん
期日は特に決めてないです。後乗りでもOKなので、告知後でもぜんぜんウェルカムです。

ちなみに今日IIJも使うことができると連絡があったので（135人OKの会場なので）。ハンダ行けるか確認します。
ハンダOKなら規模をどの程度するか次第ですね。個人的には50人以上はキツいかなと。

**Comment by n0bisuke** [comment]
Issueがあったんですね！

**Comment by MSakamaki** [comment]
NodeBots Dayですが、とりあえず以下の内容になりそう。

基本こっちの参加スタンスは「CHIRIMENのタッチ＆トライをしてもらう」
1. もくもく会ベース
2. CHIRIMENチームはブースを提供してもらえるので。CHIRIMENハードウェアを提供して、タッチ＆トライをしてもらう。
3. センサー類やハンダなどの提供は、各コミュニティや参加者自前

「確認中」
どれだけのサイズのエリアを提供してもらえるのか・・・

**Comment by gurezo** [comment]
イベントが終了したので、close
