### ISSUE TITLE
回路図についての要望（記述方法）

### ISSUE THREAD

**Issue by tadfmac** [chirimen-oh/any-issues#45]
https://github.com/chirimen-oh/shields/blob/master/CHIRIMENBasicShield/CHIRIMENBasicShield.sch
について、下記改善を検討いただきたく、お願いいたします。
- [x] 配線クロスしている部分にJunctionを配置してほしいです。端子に複数つなぐのではなく、ラインの途中でJunctionを置いて分岐が視覚的に分かるようにしないと、将来画像でも回路図を公開する場合に、交差しているだけなのか結線しているのか見分けられないので

![junction](https://cloud.githubusercontent.com/assets/5193468/16333085/56dfbe5a-3a34-11e6-8c77-b407bf5dc3c4.png)
- [ ] 回路図にもクレジットを入れませんか？誰が作ったものか分かるように

**Comment by naokisekiguchi** [comment]
@tadfmac ありがとうございます。
対応しました!
https://github.com/chirimen-oh/shields/commit/a9741adab65b474345cc0fd8bf54c8bdcffc6a6c
問題なければcloseお願いします。

**Comment by naokisekiguchi** [comment]
あークレジットの件はどうしましょう？

**Comment by tadfmac** [comment]
> 亀レスすいません。。。。

クレジットの件は特に明記がなければ主張しないということで問題ない気もしますので、一旦Closeします。
