### ISSUE TITLE
shields/CHIRIMENBasicShield について [3.3V結線忘れ?]

### ISSUE THREAD

**Issue by tadfmac** [chirimen-oh/any-issues#46]
- [x] J2に3.3Vへの結線忘れがありそうです。

![33](https://cloud.githubusercontent.com/assets/5193468/16333627/41a3268c-3a37-11e6-9598-78c063242450.png)

**Comment by naokisekiguchi** [comment]
@tadfmac 見逃してました。
対応しました!
https://github.com/chirimen-oh/shields/commit/a9741adab65b474345cc0fd8bf54c8bdcffc6a6c
問題なければcloseお願いします。

**Comment by tadfmac** [comment]
対応ありがとうございます！Closeしました。
