### ISSUE TITLE
イベントなどに対するプレス対応について

### ISSUE THREAD

**Issue by satakagi** [chirimen-oh/any-issues#48]
各種イベントに対して、メディア・プレスが取材を行うことが考えられます。
このような機会はCHIRIMEN OHの活動を社会に広めるために効果的であると期待できます。
一方で、コミュニティの意図しない報道がなされることで、マイナスの効果を与える可能性もあります。　以上の背景から、プレス対応に関する議論やプレス対応の可能性のある個別事案（案件が大きくなりそうで、別にissueを立てる場合にはそのissueへのリンク）に関するissueを立てさせていただきます。

**Comment by gurezo** [comment]
その件に関しては、下記issueの関連しているので追記します。
[ slack 参加フォームを作る #19 ](https://is.gd/5aD5TE)

**Comment by gurezo** [comment]
### [ミーティング 議事録 2016.07.02](https://is.gd/5qy3gK) より
- 上記議題に関しては、下記状況が決ってから、再議論
  - 販売予定日
  - 販売価格

**Comment by gurezo** [comment]
イベントが終了したので、close
