### ISSUE TITLE
Maker Faire Tokyo 2016 スタッフ募集

### ISSUE THREAD

**Issue by gurezo** [chirimen-oh/any-issues#51]
### お手伝い可能な方は、下記フォーマットに追記
- [ ] 08/06(土) AM
- [ ] 08/06(土) PM
- [ ] 08/07(日) AM
- [ ] 08/07(日) PM

**Comment by MSakamaki** [comment]
@msakamaki
- [x] 08/06(土) AM
- [x] 08/06(土) PM
- [ ] 08/07(日) AM
- [ ] 08/07(日) PM

**Comment by sizuhiko** [comment]
- [ ] 08/06(土) AM
- [x] 08/06(土) PM
- [x] 08/07(日) AM
- [x] 08/07(日) PM

**Comment by gurezo** [comment]
@gurezo 体調に問題なければ、下記日程お手伝いします。
- [x] 08/06(土) AM
- [x] 08/06(土) PM
- [x] 08/07(日) AM
- [x] 08/07(日) PM

**Comment by kazygumi** [comment]
今度こそはお手伝い。
- [x] 08/06(土) AM
- [x] 08/06(土) PM
- [x] 08/07(日) AM
- [x] 08/07(日) PM

**Comment by noga335** [comment]
日曜は調整中です。
- [x] 08/06(土) AM
- [x] 08/06(土) PM
- [ ] 08/07(日) AM
- [ ] 08/07(日) PM

**Comment by naokisekiguchi** [comment]
なんか全体的に見ることになりそう
- [x] 08/06(土) AM
- [x] 08/06(土) PM
- [x] 08/07(日) AM
- [x] 08/07(日) PM

**Comment by gurezo** [comment]
@okudakoさんの代打入力です。
- [x] 08/06(土) AM
- [x] 08/06(土) PM
- [x] 08/07(日) AM
- [x] 08/07(日) PM

**Comment by gurezo** [comment]
イベントが終了したので、close

**Comment by gurezo** [comment]
イベントが終了したので、close
