### ISSUE TITLE
Should change manufacturer name of board to MozOpenHard

### ISSUE THREAD

**Issue by MSakamaki** [chirimen-oh/any-issues#54]
_From @dadaa on February 3, 2016 7:41_

_Copied from original issue: MozOpenHard/CHIRIMEN#60_

**Comment by MSakamaki** [comment]
_From @dadaa on February 3, 2016 9:37_

https://github.com/MozOpenHard/device-chirimen/pull/1

**Comment by ghost** [comment]
closeでいいですよね？

**Comment by ghost** [comment]
20160429ではなぜか直っていなかった。ビルドし直した20160808で直る予定。

**Comment by ghost** [comment]
20160808で修正済
