### ISSUE TITLE
scroll bar position on Browser app

### ISSUE THREAD

**Issue by MSakamaki** [chirimen-oh/any-issues#60]
_From @naobsd on April 25, 2015 8:17_

ブラウザでスクロールバーが画面の真ん中に出てきます

![2015-04-25-171544](https://cloud.githubusercontent.com/assets/482349/7332194/cd806142-eb6e-11e4-84d0-8adcbd43303d.jpg)

_Copied from original issue: MozOpenHard/CHIRIMEN#12_

**Comment by MSakamaki** [comment]
_From @YusukeYamamoto on April 27, 2015 11:51_

phoneのビルドなのも影響しているかもしれませんね。。。
tablet, tv のビルドだとうまくいくかもしれないです。

デバッグすればすぐわかると思うので、実装も見てみたいなぁ。
※両方共GW入ってから・・

**Comment by MSakamaki** [comment]
_From @YusukeYamamoto on January 18, 2016 7:6_

2.5では解消済み。
ただ、CHIRIMENとして2.5は正式サポートでは無いので、未CLOSEとしておく。

**Comment by ghost** [comment]
20160808は2.5なのでclose
