### ISSUE TITLE
Identify what documents we must prepare

### ISSUE THREAD

**Issue by MSakamaki** [chirimen-oh/any-issues#73]
_From @dynamis on February 2, 2016 7:14_

Let's define the priority or milestone of the documents we need to prepare
- spec
  - http://mozopenhard.mozillafactory.org/techinfo#hardspec
- how to build and install instruction #58 
- how to use WebGPIO & WebI2C
- Spec and native implementation + polyfil
- existing sample codes and libraries for know GPIO/I2C devices
- how to write your own library for your own GPIO/I2C device

Where we'll write these information? MDN or Wiki or mozopnehard web site (tumblr)?
I prefer MDN since it support l10n to write both english and Japanese.

_Copied from original issue: MozOpenHard/CHIRIMEN#59_

**Comment by ghost** [comment]
Japanese documents should almost be prepared. for English documents, refer #162
