### ISSUE TITLE
JSライブラリの修正

### ISSUE THREAD

**Issue by MSakamaki** [chirimen-oh/any-issues#76]
_From @YusukeYamamoto on January 26, 2016 10:1_

議論した仕様にしたがって、webgpio.js/webi2c.jsの修正を行う
https://docs.google.com/document/d/15CJ2rqeY_AfzI8l3IMFRO48N7Y1cAg9etx_JyPLzwKc/edit

仕様通りにAPIの修正、jsonから定数を呼べるようにするがメイン?
→修正されたライブラリに合わせる形でサンプルアプリの修正も必要。

_Copied from original issue: MozOpenHard/CHIRIMEN#56_

**Comment by ghost** [comment]
作業内容が明確でないので一旦close
(#156 #164 等で対応している認識)
