### ISSUE TITLE
examplesリポジトリを作る

### ISSUE THREAD

**Issue by MSakamaki** [chirimen-oh/any-issues#8]
cihimen一つで完結できる小さなexample用
topにルール的なのを記入したREADMEだけ置いておく。

**Comment by naokisekiguchi** [comment]
これ、どんな感じでしょう？
@MSakamakiさんのpolyfill ( https://github.com/club-wot/WebGPIO )を使って手元で動作確認とれたので、何かベースがあればfabbleのサンプルを合わせて作っていきますが。

**Comment by MSakamaki** [comment]
@naokisekiguchi 
リポジトリ作りました。
https://github.com/chirimen-org/examples

あと、動作は実機で確認してないですがLED点滅のサンプルを仮であげてみました。
（問題有るなら消してOKです。）

サンプルの用にルート直下にサンプルアプリがフォルダごとに並んで行くのをイメージしています

**Comment by naokisekiguchi** [comment]
@MSakamaki さきほど微修正したpull request出しました。

それと、これは好み分かれそうなんですけど、bower前提にしますか？使ったら便利なんですけどCHIRIMEN始めようってときにnpmとbowerのインストールが必要になるのはどうだろうと思いまして。
jsにライセンス情報を追記して直接含めるのはどうでしょう？他の人の意見も欲しいですね。

**Comment by MSakamaki** [comment]
@naokisekiguchi 

> jsにライセンス情報を追記して直接含める

現時点では梱包しても問題ないですが、後々の事を考えるとpolyfillは別に出来た方が良いかなと。
polyfillを含めてしまう場合のデメリットとして、バグや仕変に追従出来なくなってしまう事が懸念されるので、最新のpolyfillに追従する方法のほうが個人的に良いかなと考えてました。

他の手段としては
1. CDNに登録する
   - CHIRIMEN本体が常にInternetに接続している必要がある。
2. 固定URLからzipでダウンロード
   - 導入手順が多少煩雑になる。
3. `git submodule`化する
   - 良さそうだけど`git clone`以外の方法で取得するとどうなるかチョットわからない

他に手段がないかちょっと考えたいですね。

**Comment by naokisekiguchi** [comment]
@MSakamaki まだpolyfillも安定していないということで、別に分けてサンプルを作っていきましょうか。他にいい手段が出てくるまでbowerでインストールする形で作ります。

もしくはcloneした時点で使えるようになっているbranchが切られてもいいのかもと思いましたが。

**Comment by MSakamaki** [comment]
@naokisekiguchi 
exampleまーじしときました、動作確認ができないの 自動テストとかでの品質チェックできないのが地味につらいですね。
