### ISSUE TITLE
WebGPIO & WebI2C 実装を Worker スレッドに

### ISSUE THREAD

**Issue by MSakamaki** [chirimen-oh/any-issues#80]
_From @dynamis on January 25, 2016 11:36_

今は Navigator を使ってるが WorkerNavigator (実装) とか使って Device Worker を立てていく形に

_Copied from original issue: MozOpenHard/CHIRIMEN#51_

**Comment by MSakamaki** [comment]
_From @YusukeYamamoto on January 26, 2016 9:55_
- [ ] WorkerNavigator 経由で WebGPIO の各メソッド を呼べるようにする
- [ ] WorkerNavigator 経由で WebI2C の各メソッド を呼べるようにする

**Comment by MSakamaki** [comment]
_From @dadaa on February 3, 2016 9:38_

i2c
https://github.com/MozOpenHard/gecko-dev/pull/1
gpio
https://github.com/MozOpenHard/gecko-dev/pull/2

**Comment by ghost** [comment]
これはもうcloseでしょうか？

**Comment by MSakamaki** [comment]
@dadaa さんがcloseと判断したらcloseで！

**Comment by dadaa** [comment]
close っすね！
