### ISSUE TITLE
curious images with screen capture with monitor 

### ISSUE THREAD

**Issue by MSakamaki** [chirimen-oh/any-issues#87]
_From @YusukeYamamoto on January 18, 2016 7:21_

スクリーンショットをとると、RGBの値がおかしい画像が取得される
他デバイスと同様、既存バグ、ポーティングが必要。

_Copied from original issue: MozOpenHard/CHIRIMEN#44_

**Comment by ghost** [comment]
20160808リリースでFirefox 51のWebIDEのScreenshotの色は問題なかった
