### ISSUE TITLE
Maker Faire Tokyo 2016 KDDIブース看板デザイン

### ISSUE THREAD

**Issue by kazygumi** [chirimen-oh/any-issues#94]
ギリギリとなってしまい申し訳ないです。

看板デザインを作成しましたので
先日のミーティングの意向と合っているか確認をお願いします。

<img width="960" alt="2016-07-07 1 34 40" src="https://cloud.githubusercontent.com/assets/10734849/16626649/d9524a10-43e4-11e6-93d4-f7576c34d192.png">

[MFT2016看板.ai.zip](https://github.com/chirimen-oh/any-issues/files/350423/MFT2016.ai.zip)

**Comment by gurezo** [comment]
@gurezo 個人はこのデザイン認識でいます。
強いて言えば、SPONSERSの箇所のどこか（最下部？）に
50音順、A-Z順と記載があれば、良いかと思います。

**Comment by kazygumi** [comment]
@gurezo さん
ありがとうございます。
SPONSERSの最下部に「※掲載は五十音順・A-Z順、敬称略」を
追記しました。

![2016-07-07 9 14 46](https://cloud.githubusercontent.com/assets/10734849/16638599/7dd9e726-4423-11e6-9400-eb4da29dea9e.png)

[MFT2016看板.ai.zip](https://github.com/chirimen-oh/any-issues/files/351144/MFT2016.ai.zip)

**Comment by kohichi000000** [comment]
Cの看板ですよね。
私のイメージは以下でしたがいかがでしょう？：

左（多分下側はほとんど見えない）：　上側のCHIRIMENのロゴ＋タイポだけにする
真ん中（通路側で一番見えるところ）：　上側は上記ご提案のまま(CHIRIMENロゴ＋タイポと簡単な説明）、下側に後援者、協力者を掲載する（つまり左にあるやつを移動）。
右（トークスペース側を向いている）：　何も載せないか、「Web x 宇宙 x Make」と書く

＃HAKUTOさんに確認なのですが、HAKUTOとCHIRIMENの露出は均等にしたいので。

**Comment by kazygumi** [comment]
了解しました。
このような感じでどうでしょうか。

![2016-07-07 12 27 01](https://cloud.githubusercontent.com/assets/10734849/16641721/4619c976-443e-11e6-8c80-9bab38447409.png)

[MFT2016看板2.ai.zip](https://github.com/chirimen-oh/any-issues/files/351352/MFT2016.2.ai.zip)

ちなみにSPONSERSのところは、
横向きのA3用紙を2枚縦並びで置けるスペースを空けています。

**Comment by kohichi000000** [comment]
ありがとうございます。私はこんなイメージでしたが、みなさんどうでしょうか？？

**Comment by sizuhiko** [comment]
私の先日の理解では最初のイメージでしたが、看板2も良いと思います

**Comment by MSakamaki** [comment]
issues整理したときにタグ我内のでeventタグ追加
あとマイルストーンとかも無いので置きました。

**Comment by kohichi000000** [comment]
皆さん特に異論なさそうなので、とりあえず案２で提案します。
スポンサーは皆さんからいただいたものを入れますね～（やっぱりスポンサーがたくさんそろっているとかっこいい）

**Comment by kohichi000000** [comment]
イベント事務局から２点コメントがありましたので、すいませんが、以下のように対応させてください。

①イベントのルールとして、通路側への（イベントスポンサー以外の）会社名、個人名の露出はできない。
⇒（ルールということで仕方ないので）CHIRIMENブース内側（もともとの @kazygumi さん看板１案どおり）にスポンサー名を移す。
②SPONSORだと何のスポンサーだかわからない（イベントのスポンサーと混同する）ので明確化してほしい
⇒「CHIRIMEN CONTRIBUTOR」と変更（実際に手を動かしてくださっている方という意味もこめて）

**Comment by kazygumi** [comment]
わかりました。夜に対応します。

**Comment by kazygumi** [comment]
取り急ぎ対応しましたー！
こちらで問題がないか確認をお願い致します〜

![2016-07-13 18 05 04](https://cloud.githubusercontent.com/assets/10734849/16797917/878260f4-4924-11e6-8a19-581e5b068219.png)

[MFT2016看板3.ai.zip](https://github.com/chirimen-oh/any-issues/files/361089/MFT2016.3.ai.zip)

**Comment by kohichi000000** [comment]
@kazygumi さん、仕事が早いですね（笑）
これ送っておきます。

**Comment by kohichi000000** [comment]
Slackにもかきましたが、ブースのロゴ掲載案です：https://www.dropbox.com/s/5qqjdextriaro0d/Maker%20Faire%20Tokyo_KDDI-0630-2.pdf?dl=0
